# Form implementation generated from reading ui file 'Admin_bar.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sqlite3
import datetime
############
##Database##
############
conn = sqlite3.connect('CIS_admin_helper.db')
cur = conn.cursor()
cur.execute('CREATE TABLE IF NOT EXISTS inventory(date TEXT, admin TEXT, itog TEXT)')
cur.execute('CREATE TABLE IF NOT EXISTS admin_bar(date TEXT, admin TEXT, position TEXT, value FLOAT, cost FLOAT)')
cur.execute('CREATE TABLE IF NOT EXISTS admins(name TEXT)')
cur.execute('CREATE TABLE IF NOT EXISTS positions (name TEXT, price FLOAT)')



class Ui_Bar(object):
    def setupUi(self, Bar):
        Bar.setObjectName("Bar")
        Bar.resize(416, 751)
        self.centralwidget = QtWidgets.QWidget(parent=Bar)
        self.centralwidget.setObjectName("centralwidget")
        self.send = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send.setGeometry(QtCore.QRect(290, 680, 89, 25))
        self.send.setObjectName("send")
        self.send.clicked.connect(self.get_result)
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(20, 680, 89, 25))
        self.back.setObjectName("back")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 371, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        cur.execute('SELECT * FROM admins')
        admins = cur.fetchall()
        for admin in admins:
            self.comboBox.addItem(admin[0])
        self.horizontalLayout.addWidget(self.comboBox)
        self.horizontalLayout.setStretch(1, 4)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 60, 371, 591))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 369, 589))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.grid = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        cur.execute('SELECT * FROM positions')
        result = cur.fetchall()
        s = 0
        for i in result:
            object_0 = QtWidgets.QLabel(f'{i[0]}')
            object_1 = QtWidgets.QDoubleSpinBox()
            object_1.setMaximum(99999)
            self.grid.addWidget(object_0,s,0)
            self.grid.addWidget(object_1, s, 1)
            s = s + 1
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        Bar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Bar)
        self.statusbar.setObjectName("statusbar")
        Bar.setStatusBar(self.statusbar)

        self.retranslateUi(Bar)
        QtCore.QMetaObject.connectSlotsByName(Bar)

    def retranslateUi(self, Bar):
        _translate = QtCore.QCoreApplication.translate
        Bar.setWindowTitle(_translate("Bar", "Бар админ"))
        self.send.setText(_translate("Bar", "Отправить"))
        self.back.setText(_translate("Bar", "Назад"))
        self.label.setText(_translate("Bar", "Имя админа"))


    def get_result(self):
        admin_name = self.comboBox.currentText()
        i = 0
        while i < self.grid.rowCount():
            name = self.grid.itemAtPosition(i, 0)
            name = name.widget().text()
            count = self.grid.itemAtPosition(i, 1)
            count = count.widget().value()
            today = datetime.datetime.now()
            to_insrt = f'{today.year}-{today.month}-{today.day}'
            if count > 0:
                cur.execute(f'SELECT * FROM positions WHERE name = "{str(name)}"')
                res = cur.fetchall()
                cur.execute(f'INSERT INTO admin_bar VALUES("{to_insrt}", "{admin_name}", "{name}", "{count}", "{res[0][1]}")')
                conn.commit()
            i = i +1

        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bar = QtWidgets.QMainWindow()
    ui = Ui_Bar()
    ui.setupUi(Bar)
    Bar.show()
    sys.exit(app.exec())
