# Form implementation generated from reading ui file 'Admin_bar.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sqlite3
import datetime

############
##Database##
############
conn = sqlite3.connect('CIS_admin_helper.db')
cur = conn.cursor()
cur.execute('CREATE TABLE IF NOT EXISTS inventory(date TEXT, admin TEXT, itog TEXT)')
cur.execute('CREATE TABLE IF NOT EXISTS admin_bar(date TEXT, admin TEXT, position TEXT, value FLOAT, cost FLOAT)')


class Ui_Bar(object):
    def setupUi(self, Bar):
        Bar.setObjectName("Bar")
        Bar.resize(416, 751)
        self.centralwidget = QtWidgets.QWidget(parent=Bar)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 70, 261, 594))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.drink5 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.drink5.setWrapping(False)
        self.drink5.setFrame(False)
        self.drink5.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drink5.setDecimals(0)
        self.drink5.setMaximum(1000.0)
        self.drink5.setObjectName("drink5")
        self.verticalLayout_2.addWidget(self.drink5)
        self.small_drink = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.small_drink.setWrapping(False)
        self.small_drink.setFrame(False)
        self.small_drink.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.small_drink.setDecimals(0)
        self.small_drink.setMaximum(1000.0)
        self.small_drink.setObjectName("small_drink")
        self.verticalLayout_2.addWidget(self.small_drink)
        self.genezis = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.genezis.setWrapping(False)
        self.genezis.setFrame(False)
        self.genezis.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.genezis.setDecimals(0)
        self.genezis.setMaximum(1000.0)
        self.genezis.setObjectName("genezis")
        self.verticalLayout_2.addWidget(self.genezis)
        self.eon = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.eon.setWrapping(False)
        self.eon.setFrame(False)
        self.eon.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.eon.setDecimals(0)
        self.eon.setMaximum(1000.0)
        self.eon.setObjectName("eon")
        self.verticalLayout_2.addWidget(self.eon)
        self.Burn = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Burn.setWrapping(False)
        self.Burn.setFrame(False)
        self.Burn.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Burn.setDecimals(0)
        self.Burn.setMaximum(1000.0)
        self.Burn.setObjectName("Burn")
        self.verticalLayout_2.addWidget(self.Burn)
        self.adrenaline = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.adrenaline.setWrapping(False)
        self.adrenaline.setFrame(False)
        self.adrenaline.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.adrenaline.setDecimals(0)
        self.adrenaline.setMaximum(1000.0)
        self.adrenaline.setObjectName("adrenaline")
        self.verticalLayout_2.addWidget(self.adrenaline)
        self.Cyberwater = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Cyberwater.setWrapping(False)
        self.Cyberwater.setFrame(False)
        self.Cyberwater.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Cyberwater.setDecimals(0)
        self.Cyberwater.setMaximum(1000.0)
        self.Cyberwater.setObjectName("Cyberwater")
        self.verticalLayout_2.addWidget(self.Cyberwater)
        self.water = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.water.setWrapping(False)
        self.water.setFrame(False)
        self.water.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.water.setDecimals(0)
        self.water.setMaximum(1000.0)
        self.water.setObjectName("water")
        self.verticalLayout_2.addWidget(self.water)
        self.Chokolate = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Chokolate.setWrapping(False)
        self.Chokolate.setFrame(False)
        self.Chokolate.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Chokolate.setDecimals(0)
        self.Chokolate.setMaximum(1000.0)
        self.Chokolate.setObjectName("Chokolate")
        self.verticalLayout_2.addWidget(self.Chokolate)
        self.Sandwich = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Sandwich.setWrapping(False)
        self.Sandwich.setFrame(False)
        self.Sandwich.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Sandwich.setDecimals(0)
        self.Sandwich.setMaximum(1000.0)
        self.Sandwich.setObjectName("Sandwich")
        self.verticalLayout_2.addWidget(self.Sandwich)
        self.roll = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.roll.setWrapping(False)
        self.roll.setFrame(False)
        self.roll.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.roll.setDecimals(0)
        self.roll.setMaximum(1000.0)
        self.roll.setObjectName("roll")
        self.verticalLayout_2.addWidget(self.roll)
        self.Soak = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Soak.setWrapping(False)
        self.Soak.setFrame(False)
        self.Soak.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Soak.setDecimals(0)
        self.Soak.setMaximum(1000.0)
        self.Soak.setObjectName("Soak")
        self.verticalLayout_2.addWidget(self.Soak)
        self.Juice = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Juice.setWrapping(False)
        self.Juice.setFrame(False)
        self.Juice.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Juice.setDecimals(0)
        self.Juice.setMaximum(1000.0)
        self.Juice.setObjectName("Juice")
        self.verticalLayout_2.addWidget(self.Juice)
        self.benergy = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.benergy.setWrapping(False)
        self.benergy.setFrame(False)
        self.benergy.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.benergy.setDecimals(0)
        self.benergy.setMaximum(1000.0)
        self.benergy.setObjectName("benergy")
        self.verticalLayout_2.addWidget(self.benergy)
        self.powercell = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.powercell.setWrapping(False)
        self.powercell.setFrame(False)
        self.powercell.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.powercell.setDecimals(0)
        self.powercell.setMaximum(1000.0)
        self.powercell.setObjectName("powercell")
        self.verticalLayout_2.addWidget(self.powercell)
        self.gorilla = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.gorilla.setWrapping(False)
        self.gorilla.setFrame(False)
        self.gorilla.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.gorilla.setDecimals(0)
        self.gorilla.setMaximum(1000.0)
        self.gorilla.setObjectName("gorilla")
        self.verticalLayout_2.addWidget(self.gorilla)
        self.Flash = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Flash.setWrapping(False)
        self.Flash.setFrame(False)
        self.Flash.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Flash.setDecimals(0)
        self.Flash.setMaximum(1000.0)
        self.Flash.setObjectName("Flash")
        self.verticalLayout_2.addWidget(self.Flash)
        self.obed = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.obed.setWrapping(False)
        self.obed.setFrame(False)
        self.obed.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.obed.setDecimals(0)
        self.obed.setMaximum(1000.0)
        self.obed.setObjectName("obed")
        self.verticalLayout_2.addWidget(self.obed)
        self.oni120 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.oni120.setWrapping(False)
        self.oni120.setFrame(False)
        self.oni120.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.oni120.setDecimals(0)
        self.oni120.setMaximum(1000.0)
        self.oni120.setObjectName("oni120")
        self.verticalLayout_2.addWidget(self.oni120)
        self.oni150 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.oni150.setWrapping(False)
        self.oni150.setFrame(False)
        self.oni150.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.oni150.setDecimals(0)
        self.oni150.setMaximum(1000.0)
        self.oni150.setObjectName("oni150")
        self.verticalLayout_2.addWidget(self.oni150)
        self.Flum = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Flum.setWrapping(False)
        self.Flum.setFrame(False)
        self.Flum.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Flum.setDecimals(0)
        self.Flum.setMaximum(1000.0)
        self.Flum.setObjectName("Flum")
        self.verticalLayout_2.addWidget(self.Flum)
        self.tornado = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.tornado.setWrapping(False)
        self.tornado.setFrame(False)
        self.tornado.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.tornado.setDecimals(0)
        self.tornado.setMaximum(1000.0)
        self.tornado.setObjectName("tornado")
        self.verticalLayout_2.addWidget(self.tornado)
        self.water_3 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.water_3.setWrapping(False)
        self.water_3.setFrame(False)
        self.water_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.water_3.setDecimals(0)
        self.water_3.setMaximum(1000.0)
        self.water_3.setObjectName("water_3")
        self.verticalLayout_2.addWidget(self.water_3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 70, 111, 591))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_4.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.send = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send.setGeometry(QtCore.QRect(290, 680, 89, 25))
        self.send.setObjectName("send")
        self.send.clicked.connect(self.send_result)
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(20, 680, 89, 25))
        self.back.setObjectName("back")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 371, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Эдик")
        self.comboBox.addItem("Лиза")
        self.comboBox.addItem("Саша")
        self.comboBox.addItem("Рома")
        self.comboBox.addItem("Рустам")
        self.comboBox.addItem("Другое")
        self.horizontalLayout.addWidget(self.comboBox)
        self.horizontalLayout.setStretch(1, 4)
        Bar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Bar)
        self.statusbar.setObjectName("statusbar")
        Bar.setStatusBar(self.statusbar)

        self.retranslateUi(Bar)
        QtCore.QMetaObject.connectSlotsByName(Bar)

    def retranslateUi(self, Bar):
        _translate = QtCore.QCoreApplication.translate
        Bar.setWindowTitle(_translate("Bar", "Бар админ"))
        self.label_2.setText(_translate("Bar", "Напиток 0,5"))
        self.label_3.setText(_translate("Bar", "Напиток 0,33"))
        self.label_4.setText(_translate("Bar", "Genezis"))
        self.label_5.setText(_translate("Bar", "E-on"))
        self.label_6.setText(_translate("Bar", "Burn"))
        self.label_7.setText(_translate("Bar", "Adrenaline"))
        self.label_8.setText(_translate("Bar", "Cyberwater"))
        self.label_9.setText(_translate("Bar", "Вода"))
        self.label_10.setText(_translate("Bar", "Шоколад"))
        self.label_11.setText(_translate("Bar", "Сэндвич"))
        self.label_12.setText(_translate("Bar", "Сэндвич ролл"))
        self.label_13.setText(_translate("Bar", "Soak"))
        self.label_14.setText(_translate("Bar", "Соки"))
        self.label_15.setText(_translate("Bar", "benergy"))
        self.label_16.setText(_translate("Bar", "Powercell"))
        self.label_17.setText(_translate("Bar", "Gorilla"))
        self.label_18.setText(_translate("Bar", "Flash"))
        self.label_19.setText(_translate("Bar", "Обед"))
        self.label_20.setText(_translate("Bar", "Онигири 120"))
        self.label_21.setText(_translate("Bar", "Онигири 150"))
        self.label_22.setText(_translate("Bar", "Flum"))
        self.label_23.setText(_translate("Bar", "Tornado"))
        self.label_24.setText(_translate("Bar", "Чай Gorilla"))
        self.send.setText(_translate("Bar", "Отправить"))
        self.back.setText(_translate("Bar", "Назад"))
        self.label.setText(_translate("Bar", "Имя админа"))


    def send_result(self):
        admin_name = self.comboBox.currentText()
        powercell = {
            'name': 'Powercell',
            'price' : 130,
            'value': self.powercell.value()
        }
        gorilla = {
            'name' : 'Gorilla',
            'price' : 120,
            'value' : self.gorilla.value()
        }
        flash = {
            'name' : 'Flash',
            'price' : 100,
            'value' : self.Flash.value()
        }
        obed = {
            'name' : 'Обед',
            'price' : 200,
            'value' : self.obed.value()
        }
        oni_150 = {
            'name' : 'Онигири 150',
            'price' : 150,
            'value' : self.oni150.value()
        }
        oni_120 = {
            'name' : 'Онигири 120',
            'price' : 120,
            'value' : self.oni120.value()
        }
        flum = {
            'name' : 'Flum',
            'price' : 1400,
            'value' : self.Flum.value()
        }
        benergy = {
            'name' : 'Benergy',
            'price' : 130,
            'value' : self.benergy.value()
            }
        juice = {
            'name' : 'Сок',
            'price' : 100,
            'value' : self.Juice.value()
        }
        soak = {
            'name' : 'Soak',
            'price' : 1400,
            'value' : self.Soak.value()
        }
        roll = {
            'name' : 'Сендвич ролл',
            'price' : 180,
            'value' : self.roll.value()
        }
        snwch = {
            'name' : 'Сендвич',
            'price' : 150,
            'value' : self.Sandwich.value()
        }
        choko = {
            'name' : 'Шоколадка',
            'price' : 100,
            'value' : self.Chokolate.value()
        }
        water = {
            'name' : 'Вода',
            'price' : 50,
            'value' : self.water.value()
        }
        cyberwater = {
            'name' : 'Cyberwater',
            'price' : 130,
            'value' : self.Cyberwater.value()
        }
        adrenaline = {
            'name' : 'Adrenaline',
            'price' : 150,
            'value' : self.adrenaline.value()
        }
        burn = {
            'name' : 'Burn',
            'price' : 150,
            'value' : self.Burn.value()
        }
        eon = {
            'name' : 'E-On',
            'price' : 120,
            'value' : self.eon.value()
        }
        genezis = {
            'name' : 'Genezis',
            'price' : 110,
            'value' : self.genezis.value()
        }
        drink5 = {
            'name' : 'Напиток 0.5',
            'price' : 110,
            'value' : self.drink5.value()
        }
        small_drink = {
            'name' : 'Напиток 0.33',
            'price' : 70,
            'value' : self.small_drink.value()
        }
        tornado = {
            'name' : 'Tornado',
            'price' : 100,
            'value' : self.tornado.value()
        }
        tea_gorilla = {
            'name' : 'Чай Gorilla',
            'price' : 100,
            'value' : self.water_3.value()
        }
        item_list = [powercell,gorilla,flash,obed,oni_120,oni_150,flum,benergy,juice,soak,roll,snwch,choko,water,cyberwater,adrenaline,burn,eon,genezis,drink5,small_drink, tornado, tea_gorilla]
        for item in item_list:
            if item['value'] > 0:
                name, value = item['name'], item['value']
                cost = value * item['price']
                today = datetime.datetime.now()
                to_insrt = f'{today.year}-{today.month}-{today.day}'
                cur.execute(f'INSERT INTO admin_bar VALUES("{to_insrt}", "{admin_name}", "{name}", "{value}", "{cost}")')
                conn.commit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bar = QtWidgets.QMainWindow()
    ui = Ui_Bar()
    ui.setupUi(Bar)
    Bar.show()
    sys.exit(app.exec())
