

from page import Ui_MainWindow
from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess
from datetime import datetime

class Inventory(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(616, 797)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 720, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.go_back)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 720, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.send)
        self.label_43 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(30, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(340, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 70, 151, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.drink5 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.drink5.setWrapping(False)
        self.drink5.setFrame(False)
        self.drink5.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drink5.setDecimals(0)
        self.drink5.setMaximum(1000.0)
        self.drink5.setObjectName("drink5")
        self.verticalLayout_2.addWidget(self.drink5)
        self.small_drink = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.small_drink.setWrapping(False)
        self.small_drink.setFrame(False)
        self.small_drink.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.small_drink.setDecimals(0)
        self.small_drink.setMaximum(1000.0)
        self.small_drink.setObjectName("small_drink")
        self.verticalLayout_2.addWidget(self.small_drink)
        self.genezis = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.genezis.setWrapping(False)
        self.genezis.setFrame(False)
        self.genezis.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.genezis.setDecimals(0)
        self.genezis.setMaximum(1000.0)
        self.genezis.setObjectName("genezis")
        self.verticalLayout_2.addWidget(self.genezis)
        self.eon = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.eon.setWrapping(False)
        self.eon.setFrame(False)
        self.eon.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.eon.setDecimals(0)
        self.eon.setMaximum(1000.0)
        self.eon.setObjectName("eon")
        self.verticalLayout_2.addWidget(self.eon)
        self.Burn = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Burn.setWrapping(False)
        self.Burn.setFrame(False)
        self.Burn.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Burn.setDecimals(0)
        self.Burn.setMaximum(1000.0)
        self.Burn.setObjectName("Burn")
        self.verticalLayout_2.addWidget(self.Burn)
        self.adrenaline = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.adrenaline.setWrapping(False)
        self.adrenaline.setFrame(False)
        self.adrenaline.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.adrenaline.setDecimals(0)
        self.adrenaline.setMaximum(1000.0)
        self.adrenaline.setObjectName("adrenaline")
        self.verticalLayout_2.addWidget(self.adrenaline)
        self.Cyberwater = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Cyberwater.setWrapping(False)
        self.Cyberwater.setFrame(False)
        self.Cyberwater.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Cyberwater.setDecimals(0)
        self.Cyberwater.setMaximum(1000.0)
        self.Cyberwater.setObjectName("Cyberwater")
        self.verticalLayout_2.addWidget(self.Cyberwater)
        self.water = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.water.setWrapping(False)
        self.water.setFrame(False)
        self.water.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.water.setDecimals(0)
        self.water.setMaximum(1000.0)
        self.water.setObjectName("water")
        self.verticalLayout_2.addWidget(self.water)
        self.Chokolate = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Chokolate.setWrapping(False)
        self.Chokolate.setFrame(False)
        self.Chokolate.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Chokolate.setDecimals(0)
        self.Chokolate.setMaximum(1000.0)
        self.Chokolate.setObjectName("Chokolate")
        self.verticalLayout_2.addWidget(self.Chokolate)
        self.Sandwich = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Sandwich.setWrapping(False)
        self.Sandwich.setFrame(False)
        self.Sandwich.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Sandwich.setDecimals(0)
        self.Sandwich.setMaximum(1000.0)
        self.Sandwich.setObjectName("Sandwich")
        self.verticalLayout_2.addWidget(self.Sandwich)
        self.roll = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.roll.setWrapping(False)
        self.roll.setFrame(False)
        self.roll.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.roll.setDecimals(0)
        self.roll.setMaximum(1000.0)
        self.roll.setObjectName("roll")
        self.verticalLayout_2.addWidget(self.roll)
        self.Soak = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Soak.setWrapping(False)
        self.Soak.setFrame(False)
        self.Soak.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Soak.setDecimals(0)
        self.Soak.setMaximum(1000.0)
        self.Soak.setObjectName("Soak")
        self.verticalLayout_2.addWidget(self.Soak)
        self.Juice = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Juice.setWrapping(False)
        self.Juice.setFrame(False)
        self.Juice.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Juice.setDecimals(0)
        self.Juice.setMaximum(1000.0)
        self.Juice.setObjectName("Juice")
        self.verticalLayout_2.addWidget(self.Juice)
        self.benergy = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.benergy.setWrapping(False)
        self.benergy.setFrame(False)
        self.benergy.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.benergy.setDecimals(0)
        self.benergy.setMaximum(1000.0)
        self.benergy.setObjectName("benergy")
        self.verticalLayout_2.addWidget(self.benergy)
        self.powercell = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.powercell.setWrapping(False)
        self.powercell.setFrame(False)
        self.powercell.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.powercell.setDecimals(0)
        self.powercell.setMaximum(1000.0)
        self.powercell.setObjectName("powercell")
        self.verticalLayout_2.addWidget(self.powercell)
        self.gorilla = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.gorilla.setWrapping(False)
        self.gorilla.setFrame(False)
        self.gorilla.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.gorilla.setDecimals(0)
        self.gorilla.setMaximum(1000.0)
        self.gorilla.setObjectName("gorilla")
        self.verticalLayout_2.addWidget(self.gorilla)
        self.Flash = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Flash.setWrapping(False)
        self.Flash.setFrame(False)
        self.Flash.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Flash.setDecimals(0)
        self.Flash.setMaximum(1000.0)
        self.Flash.setObjectName("Flash")
        self.verticalLayout_2.addWidget(self.Flash)
        self.obed = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.obed.setWrapping(False)
        self.obed.setFrame(False)
        self.obed.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.obed.setDecimals(0)
        self.obed.setMaximum(1000.0)
        self.obed.setObjectName("obed")
        self.verticalLayout_2.addWidget(self.obed)
        self.oni120 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.oni120.setWrapping(False)
        self.oni120.setFrame(False)
        self.oni120.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.oni120.setDecimals(0)
        self.oni120.setMaximum(1000.0)
        self.oni120.setObjectName("oni120")
        self.verticalLayout_2.addWidget(self.oni120)
        self.oni150 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.oni150.setWrapping(False)
        self.oni150.setFrame(False)
        self.oni150.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.oni150.setDecimals(0)
        self.oni150.setMaximum(1000.0)
        self.oni150.setObjectName("oni150")
        self.verticalLayout_2.addWidget(self.oni150)
        self.Flum = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Flum.setWrapping(False)
        self.Flum.setFrame(False)
        self.Flum.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Flum.setDecimals(0)
        self.Flum.setMaximum(1000.0)
        self.Flum.setObjectName("Flum")
        self.verticalLayout_2.addWidget(self.Flum)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(450, 70, 151, 541))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.drink5_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.drink5_1.setWrapping(False)
        self.drink5_1.setFrame(False)
        self.drink5_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drink5_1.setDecimals(0)
        self.drink5_1.setMaximum(1000.0)
        self.drink5_1.setObjectName("drink5_1")
        self.verticalLayout_3.addWidget(self.drink5_1)
        self.small_drink_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.small_drink_1.setWrapping(False)
        self.small_drink_1.setFrame(False)
        self.small_drink_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.small_drink_1.setDecimals(0)
        self.small_drink_1.setMaximum(1000.0)
        self.small_drink_1.setObjectName("small_drink_1")
        self.verticalLayout_3.addWidget(self.small_drink_1)
        self.genezis_2 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.genezis_2.setWrapping(False)
        self.genezis_2.setFrame(False)
        self.genezis_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.genezis_2.setDecimals(0)
        self.genezis_2.setMaximum(1000.0)
        self.genezis_2.setObjectName("genezis_2")
        self.verticalLayout_3.addWidget(self.genezis_2)
        self.eon_2 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.eon_2.setWrapping(False)
        self.eon_2.setFrame(False)
        self.eon_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.eon_2.setDecimals(0)
        self.eon_2.setMaximum(1000.0)
        self.eon_2.setObjectName("eon_2")
        self.verticalLayout_3.addWidget(self.eon_2)
        self.burn_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.burn_1.setWrapping(False)
        self.burn_1.setFrame(False)
        self.burn_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.burn_1.setDecimals(0)
        self.burn_1.setMaximum(1000.0)
        self.burn_1.setObjectName("burn_1")
        self.verticalLayout_3.addWidget(self.burn_1)
        self.adrenaline_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.adrenaline_1.setWrapping(False)
        self.adrenaline_1.setFrame(False)
        self.adrenaline_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.adrenaline_1.setDecimals(0)
        self.adrenaline_1.setMaximum(1000.0)
        self.adrenaline_1.setObjectName("adrenaline_1")
        self.verticalLayout_3.addWidget(self.adrenaline_1)
        self.Cyberwater_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.Cyberwater_1.setWrapping(False)
        self.Cyberwater_1.setFrame(False)
        self.Cyberwater_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Cyberwater_1.setDecimals(0)
        self.Cyberwater_1.setMaximum(1000.0)
        self.Cyberwater_1.setObjectName("Cyberwater_1")
        self.verticalLayout_3.addWidget(self.Cyberwater_1)
        self.Water_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.Water_1.setWrapping(False)
        self.Water_1.setFrame(False)
        self.Water_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Water_1.setDecimals(0)
        self.Water_1.setMaximum(1000.0)
        self.Water_1.setObjectName("Water_1")
        self.verticalLayout_3.addWidget(self.Water_1)
        self.choko_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.choko_1.setWrapping(False)
        self.choko_1.setFrame(False)
        self.choko_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.choko_1.setDecimals(0)
        self.choko_1.setMaximum(1000.0)
        self.choko_1.setObjectName("choko_1")
        self.verticalLayout_3.addWidget(self.choko_1)
        self.sandwitch_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.sandwitch_1.setWrapping(False)
        self.sandwitch_1.setFrame(False)
        self.sandwitch_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.sandwitch_1.setDecimals(0)
        self.sandwitch_1.setMaximum(1000.0)
        self.sandwitch_1.setObjectName("sandwitch_1")
        self.verticalLayout_3.addWidget(self.sandwitch_1)
        self.roll_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.roll_1.setWrapping(False)
        self.roll_1.setFrame(False)
        self.roll_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.roll_1.setDecimals(0)
        self.roll_1.setMaximum(1000.0)
        self.roll_1.setObjectName("roll_1")
        self.verticalLayout_3.addWidget(self.roll_1)
        self.Soak_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.Soak_1.setWrapping(False)
        self.Soak_1.setFrame(False)
        self.Soak_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Soak_1.setDecimals(0)
        self.Soak_1.setMaximum(1000.0)
        self.Soak_1.setObjectName("Soak_1")
        self.verticalLayout_3.addWidget(self.Soak_1)
        self.juice_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.juice_1.setWrapping(False)
        self.juice_1.setFrame(False)
        self.juice_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.juice_1.setDecimals(0)
        self.juice_1.setMaximum(1000.0)
        self.juice_1.setObjectName("juice_1")
        self.verticalLayout_3.addWidget(self.juice_1)
        self.benergy_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.benergy_1.setWrapping(False)
        self.benergy_1.setFrame(False)
        self.benergy_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.benergy_1.setDecimals(0)
        self.benergy_1.setMaximum(1000.0)
        self.benergy_1.setObjectName("benergy_1")
        self.verticalLayout_3.addWidget(self.benergy_1)
        self.powercell_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.powercell_1.setWrapping(False)
        self.powercell_1.setFrame(False)
        self.powercell_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.powercell_1.setDecimals(0)
        self.powercell_1.setMaximum(1000.0)
        self.powercell_1.setObjectName("powercell_1")
        self.verticalLayout_3.addWidget(self.powercell_1)
        self.Gorilla_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.Gorilla_1.setWrapping(False)
        self.Gorilla_1.setFrame(False)
        self.Gorilla_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Gorilla_1.setDecimals(0)
        self.Gorilla_1.setMaximum(1000.0)
        self.Gorilla_1.setObjectName("Gorilla_1")
        self.verticalLayout_3.addWidget(self.Gorilla_1)
        self.Flash_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.Flash_1.setWrapping(False)
        self.Flash_1.setFrame(False)
        self.Flash_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Flash_1.setDecimals(0)
        self.Flash_1.setMaximum(1000.0)
        self.Flash_1.setObjectName("Flash_1")
        self.verticalLayout_3.addWidget(self.Flash_1)
        self.obed_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.obed_1.setWrapping(False)
        self.obed_1.setFrame(False)
        self.obed_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.obed_1.setDecimals(0)
        self.obed_1.setMaximum(1000.0)
        self.obed_1.setObjectName("obed_1")
        self.verticalLayout_3.addWidget(self.obed_1)
        self.oni120_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.oni120_1.setWrapping(False)
        self.oni120_1.setFrame(False)
        self.oni120_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.oni120_1.setDecimals(0)
        self.oni120_1.setMaximum(1000.0)
        self.oni120_1.setObjectName("oni120_1")
        self.verticalLayout_3.addWidget(self.oni120_1)
        self.oni150_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.oni150_1.setWrapping(False)
        self.oni150_1.setFrame(False)
        self.oni150_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.oni150_1.setDecimals(0)
        self.oni150_1.setMaximum(1000.0)
        self.oni150_1.setObjectName("oni150_1")
        self.verticalLayout_3.addWidget(self.oni150_1)
        self.flum_1 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.flum_1.setWrapping(False)
        self.flum_1.setFrame(False)
        self.flum_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.flum_1.setDecimals(0)
        self.flum_1.setMaximum(1000.0)
        self.flum_1.setObjectName("flum_1")
        self.verticalLayout_3.addWidget(self.flum_1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 70, 111, 539))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(340, 70, 111, 539))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_22 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_5.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_5.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_5.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_5.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_5.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_5.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_5.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_5.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_5.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_5.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_5.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_5.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_5.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_5.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_5.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_5.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_5.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_5.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_5.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_5.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_5.addWidget(self.label_42)
        self.label_45 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(20, 650, 161, 31))
        self.label_45.setObjectName("label_45")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(180, 650, 201, 31))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Colizeum Tool"))
        self.pushButton.setText(_translate("MainWindow", "Назад"))
        self.pushButton_2.setText(_translate("MainWindow", "Отправить"))
        self.label_43.setText(_translate("MainWindow", "В проге"))
        self.label_44.setText(_translate("MainWindow", "На складе"))
        self.label.setText(_translate("MainWindow", "Напиток 0,5"))
        self.label_2.setText(_translate("MainWindow", "Напиток 0,33"))
        self.label_3.setText(_translate("MainWindow", "Genezis"))
        self.label_4.setText(_translate("MainWindow", "E-on"))
        self.label_5.setText(_translate("MainWindow", "Burn"))
        self.label_6.setText(_translate("MainWindow", "Adrenaline"))
        self.label_7.setText(_translate("MainWindow", "Cyberwater"))
        self.label_8.setText(_translate("MainWindow", "Вода"))
        self.label_9.setText(_translate("MainWindow", "Шоколад"))
        self.label_10.setText(_translate("MainWindow", "Сэндвич"))
        self.label_11.setText(_translate("MainWindow", "Сэндвич ролл"))
        self.label_12.setText(_translate("MainWindow", "Soak"))
        self.label_13.setText(_translate("MainWindow", "Соки"))
        self.label_14.setText(_translate("MainWindow", "benergy"))
        self.label_15.setText(_translate("MainWindow", "Powercell"))
        self.label_16.setText(_translate("MainWindow", "Gorilla"))
        self.label_17.setText(_translate("MainWindow", "Flash"))
        self.label_18.setText(_translate("MainWindow", "Обед"))
        self.label_19.setText(_translate("MainWindow", "Онигири 120"))
        self.label_20.setText(_translate("MainWindow", "Онигири 150"))
        self.label_21.setText(_translate("MainWindow", "Flum"))
        self.label_22.setText(_translate("MainWindow", "Напиток 0,5"))
        self.label_23.setText(_translate("MainWindow", "Напиток 0,33"))
        self.label_24.setText(_translate("MainWindow", "Genezis"))
        self.label_25.setText(_translate("MainWindow", "E-on"))
        self.label_26.setText(_translate("MainWindow", "Burn"))
        self.label_27.setText(_translate("MainWindow", "Adrenaline"))
        self.label_28.setText(_translate("MainWindow", "Cyberwater"))
        self.label_29.setText(_translate("MainWindow", "Вода"))
        self.label_30.setText(_translate("MainWindow", "Шоколад"))
        self.label_31.setText(_translate("MainWindow", "Сэндвич"))
        self.label_32.setText(_translate("MainWindow", "Сэндвич ролл"))
        self.label_33.setText(_translate("MainWindow", "Soak"))
        self.label_34.setText(_translate("MainWindow", "Соки"))
        self.label_35.setText(_translate("MainWindow", "benergy"))
        self.label_36.setText(_translate("MainWindow", "Powercell"))
        self.label_37.setText(_translate("MainWindow", "Gorilla"))
        self.label_38.setText(_translate("MainWindow", "Flash"))
        self.label_39.setText(_translate("MainWindow", "Обед"))
        self.label_40.setText(_translate("MainWindow", "Онигири 120"))
        self.label_41.setText(_translate("MainWindow", "Онигири 150"))
        self.label_42.setText(_translate("MainWindow", "Flum"))
        self.label_45.setText(_translate("MainWindow", "Имя администратора:"))

    def send(self):
       import time
       admin = self.textEdit.toPlainText()
       big_1 = self.drink5.value()
       big_2 = self.drink5_1.value()
       small_1 = self.small_drink.value()
       small_2 = self.small_drink_1.value()
       powercell_itog = self.powercell_1.value() - self.powercell.value()
       gorilla_itog = self.Gorilla_1.value() - self.gorilla.value()
       flah_itg = self.Flash_1.value() - self.Flash.value()
       obed_itg = self.obed_1.value() - self.obed.value()
       oni_150_itg = self.oni150_1.value() - self.oni150.value()
       flum_itg = self.flum_1.value() - self.Flum.value()
       benergy_itog = self.benergy_1.value() - self.benergy.value()
       jc_itg = self.juice_1.value() - self.Juice.value()
       Soak_itg = self.Soak_1.value() - self.Soak.value()
       roll_itg = self.roll_1.value() - self.roll.value()
       sndw_itg = self.sandwitch_1.value() - self.Sandwich.value()
       chokolate_itog = self.choko_1.value() - self.Chokolate.value()
       wtr_itg = self.Water_1.value() - self.water.value()
       cyberwater_itog = self.Cyberwater_1.value() - self.Cyberwater.value()
       arenaline_itog = self.adrenaline_1.value() - self.adrenaline.value()
       burn_itog = self.burn_1.value() - self.Burn.value()
       eon_itog = self.eon_2.value() - self.eon.value()
       genezis_itog = self.genezis_2.value() - self.genezis.value()
       onigiri_120_itog = self.oni120_1.value() - self.oni120.value()
       drink_big_itog = big_2-big_1
       small_drink_itog = small_2 - small_1
       time_now = datetime.now()



       result = open('result.txt', 'w')
       result.write(f'Дата: {time_now.year}-{time_now.month}-{time_now.day}\nВремя: {time_now.hour}:{time_now.minute}\nАдминистратор: {admin}\n\nPowercell - ({powercell_itog})\nGorilla - ({gorilla_itog})\nFlash - ({flah_itg})\nОбед - ({obed_itg})\nОнигири 150 - ({oni_150_itg})\nОнигири 120 - ({onigiri_120_itog})\nFlum - ({flum_itg})\nBenergy - ({benergy_itog})\nСок - ({jc_itg})\nSoak - ({Soak_itg})\nРолл - ({roll_itg})\nСендвич - ({sndw_itg})\nШоколад - ({chokolate_itog})\nВода - ({wtr_itg})\nCyberwater - ({cyberwater_itog})\nAdrenaline - ({arenaline_itog})\nBurn - ({burn_itog})\nE-on - ({eon_itog})\nGenezis - ({genezis_itog})\nНапиток 0,5 - ({drink_big_itog})\nНапиток 0,33 - ({small_drink_itog})')
       result.close()
       telegram = subprocess.Popen(['python3', 'tg_bot.py'])
       time.sleep(1)
       telegram.terminate()
    def go_back(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Inventory()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
