# Form implementation generated from reading ui file 'Colizeum Tool_second.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sqlite3
import datetime
############
##Database##
############
conn = sqlite3.connect('CIS_admin_helper.db')
cur = conn.cursor()
cur.execute('CREATE TABLE IF NOT EXISTS inventory(date TEXT, admin TEXT, itog TEXT)')
cur.execute('CREATE TABLE IF NOT EXISTS admin_bar(date TEXT, admin TEXT, position TEXT, value FLOAT, cost FLOAT)')
cur.execute('CREATE TABLE IF NOT EXISTS admins(name TEXT)')
cur.execute('CREATE TABLE IF NOT EXISTS positions (name TEXT, price FLOAT)')


class Inventory(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(616, 797)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 720, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 720, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.get_result)
        self.in_prog_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.in_prog_label.setGeometry(QtCore.QRect(20, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.in_prog_label.setFont(font)
        self.in_prog_label.setObjectName("in_prog_label")
        self.at_club_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.at_club_label.setGeometry(QtCore.QRect(340, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.at_club_label.setFont(font)
        self.at_club_label.setObjectName("at_club_label")
        self.label_name_admin = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_admin.setGeometry(QtCore.QRect(20, 650, 161, 31))
        self.label_name_admin.setObjectName("label_name_admin")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 70, 250, 540))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.content_widget = QtWidgets.QWidget()
        self.content_widget.setGeometry(QtCore.QRect(0, 0, 248, 538))
        self.content_widget.setObjectName("content_widget")
        self.grid = QtWidgets.QGridLayout(self.content_widget)
        self.label_1 = QtWidgets.QLabel('Label')
        cur.execute('SELECT * FROM positions')
        result = cur.fetchall()
        self.dic = {}
        s = 0
        for i in result:
            self.dic[str(i)] = QtWidgets.QLabel(f'{i[0]}')
            object_1 = QtWidgets.QDoubleSpinBox()
            object_1.setMaximum(99999)
            self.grid.addWidget(self.dic[str(i)], s, 0)
            self.grid.addWidget(object_1, s, 1)
            s = s+1
        self.scrollArea.setWidget(self.content_widget)
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(340, 70, 250, 540))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.content_widget_1 = QtWidgets.QWidget()
        self.content_widget_1.setGeometry(QtCore.QRect(0, 0, 248, 538))
        self.content_widget_1.setObjectName("content_widget_1")
        self.grid_1 = QtWidgets.QGridLayout(self.content_widget_1)
        s = 0
        for i in result:
            object_0 = QtWidgets.QLabel(f'{i[0]}')
            object_1 = QtWidgets.QDoubleSpinBox()
            object_1.setMaximum(99999)
            self.grid_1.addWidget(object_0, s, 0)
            self.grid_1.addWidget(object_1, s, 1)
            s = s+1
        self.scrollArea_2.setWidget(self.content_widget_1)
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(190, 650, 201, 31))
        self.comboBox.setObjectName("comboBox")
        cur.execute('SELECT * FROM admins')
        admins = cur.fetchall()
        for admin in admins:
            self.comboBox.addItem(admin[0])
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Colizeum Tool"))
        self.pushButton.setText(_translate("MainWindow", "Назад"))
        self.pushButton_2.setText(_translate("MainWindow", "Отправить"))
        self.in_prog_label.setText(_translate("MainWindow", "В проге"))
        self.at_club_label.setText(_translate("MainWindow", "На складе"))
        self.label_name_admin.setText(_translate("MainWindow", "Имя администратора:"))

    def get_result(self):
        admin_name = self.comboBox.currentText()


        i = 0
        today = datetime.datetime.now()
        date = f'{today.year}-{today.month}-{today.day}'
        to_insrt = f'{today.year}-{today.month}-{today.day}\n\n{admin_name}\n\n'
        to_bd = ''
        while i < self.grid.rowCount():
            name = self.grid.itemAtPosition(i,0)
            name = name.widget().text()
            in_program = self.grid.itemAtPosition(i,1)
            in_program = in_program.widget()

            at_club = self.grid_1.itemAtPosition(i,1)
            at_club = at_club.widget()

            itog = at_club.value() - in_program.value()
            i = i +1

            to_insrt += f'{name}:   {itog}\n'
            to_bd += f'{name}:   {itog}\n'
        result = open('result.txt', 'w')
        result.write(to_insrt)
        cur.execute(f'INSERT INTO inventory VALUES("{date}", "{admin_name}", "{to_bd}")')
        conn.commit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Inventory()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
