# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
import time
from PyQt6 import QtCore, QtGui, QtWidgets
############
##Database##
############
conn = sqlite3.connect('CIS_admin_helper.db')
cur = conn.cursor()
cur.execute('CREATE TABLE IF NOT EXISTS inventory(date TEXT, admin TEXT, itog TEXT)')
cur.execute('CREATE TABLE IF NOT EXISTS admin_bar(date TEXT, admin TEXT, position TEXT, value FLOAT, cost FLOAT)')
cur.execute('CREATE TABLE IF NOT EXISTS admins(name TEXT)')
cur.execute('CREATE TABLE IF NOT EXISTS positions (name TEXT, price FLOAT)')

class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(850, 900)
        self.centralwidget = QtWidgets.QWidget(parent=settings)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 491, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        ##################
        ##Список админов##
        ##################
        self.List_admins_widget = QtWidgets.QListWidget(parent=self.verticalLayoutWidget)
        self.List_admins_widget.setObjectName("List_admins_widget")
        self.List_admins_widget.clicked.connect(self.admin_name_clicked)
        self.verticalLayout.addWidget(self.List_admins_widget)
        cur.execute('SELECT * FROM admins')
        admins = cur.fetchall()
        for admin in admins:
            self.List_admins_widget.addItem(admin[0])
        
        ########################
        ##Выбранное имя админа##
        ########################
        self.list_admins_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.list_admins_label.setGeometry(QtCore.QRect(20, 20, 281, 17))
        self.list_admins_label.setObjectName("list_admins_label")

        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 270, 321, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")

        ######################
        ##Текст ошибка админ##
        ######################
        self.error_admin_label =QtWidgets.QLabel(parent=self.centralwidget)
        self.error_admin_label.setVisible(False)
        self.error_admin_label.setGeometry(750,90,61,31)
        self.error_admin_label.setText('Ошибка')
        self.error_admin_label.setStyleSheet("color: rgb(192, 28, 40);")

        ########################
        ##Текст ошибка позиция##
        ########################
        self.error_position_label =QtWidgets.QLabel(parent=self.centralwidget)
        self.error_position_label.setVisible(False)
        self.error_position_label.setGeometry(670,450,61,21)
        self.error_position_label.setText('Ошибка')
        self.error_position_label.setStyleSheet("color: rgb(192, 28, 40);")

        self.name_admin_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.name_admin_label.setVisible(False)
        self.name_admin_label.setObjectName("name_admin_label")
        self.horizontalLayout.addWidget(self.name_admin_label)
        self.del_admin_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.del_admin_btn.setVisible(False)
        self.del_admin_btn.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"color: rgb(192, 28, 40);")
        self.del_admin_btn.setObjectName("del_admin_btn")
        self.del_admin_btn.clicked.connect(self.admin_del)
        self.horizontalLayout.addWidget(self.del_admin_btn)
        self.add_admin_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.add_admin_label.setGeometry(QtCore.QRect(530, 20, 171, 17))
        self.add_admin_label.setObjectName("add_admin_label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(530, 50, 281, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Name_add_admin = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.Name_add_admin.setObjectName("Name_add_admin")
        self.horizontalLayout_2.addWidget(self.Name_add_admin)
        self.add_admin_text_field = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_2)
        self.add_admin_text_field.setObjectName("add_admin_text_field")
        self.horizontalLayout_2.addWidget(self.add_admin_text_field)
        self.add_admin_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.add_admin_btn.setEnabled(False)
        self.add_admin_btn.setStyleSheet("color: rgb(69, 186, 4);\n"
"background-color: rgb(35, 35, 35);")
        self.add_admin_btn.setObjectName("add_admin_btn")
        self.add_admin_btn.clicked.connect(self.add_admin)
        self.horizontalLayout_2.addWidget(self.add_admin_btn)
        self.add_admin_text_field.textChanged.connect(self.activate_add_admin)        #Активируем кнопку
        self.item_list = QtWidgets.QLabel(parent=self.centralwidget)
        self.item_list.setGeometry(QtCore.QRect(20, 330, 251, 17))
        self.item_list.setObjectName("item_list")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 360, 491, 411))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        ###########################
        ##Список с позициями бара##
        ###########################
        self.list_item_widget = QtWidgets.QListWidget(parent=self.verticalLayoutWidget_2)
        self.list_item_widget.setObjectName("list_item_widget")
        self.verticalLayout_2.addWidget(self.list_item_widget)
        self.list_item_widget.clicked.connect(self.item_clicked)
        cur.execute('SELECT * FROM positions')
        self.items = cur.fetchall()
        for item in self.items:
            self.list_item_widget.addItem(f'{item[0]} | {item[1]}')


        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 780, 321, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        ##################################
        ##Наименование выбранной позиции##
        ##################################
        self.name_item_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.name_item_label.setVisible(False)
        self.name_item_label.setObjectName("name_item_label")
        self.horizontalLayout_3.addWidget(self.name_item_label)

        ###########################
        ##Кнопка удаления позиции##
        ###########################
        self.delete_item_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.delete_item_btn.setVisible(False)
        self.delete_item_btn.setStyleSheet("color: rgb(192, 28, 40);\n"
"background-color: rgb(35, 35, 35);")
        self.delete_item_btn.setObjectName("delete_item_btn")
        self.delete_item_btn.clicked.connect(self.del_item)

        self.horizontalLayout_3.addWidget(self.delete_item_btn)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(530, 360, 291, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.item_name_label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.item_name_label.setObjectName("item_name_label")
        self.gridLayout.addWidget(self.item_name_label, 0, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget)
        self.doubleSpinBox.setMaximum(99999999.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.Item_name_field = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.Item_name_field.setObjectName("Item_name_field")
        self.Item_name_field.textChanged.connect(self.activate_add_item)      #Активируем кнопку
        self.gridLayout.addWidget(self.Item_name_field, 0, 1, 1, 1)

        ###Стоимость позиции
        self.item_cost_label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.item_cost_label.setObjectName("item_cost_label")
        self.gridLayout.addWidget(self.item_cost_label, 1, 0, 1, 1)

        ###Кнопка добавить позицию бара
        self.add_item_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_item_btn.setEnabled(False)
        self.add_item_btn.setGeometry(QtCore.QRect(740, 450, 80, 25))
        self.add_item_btn.setStyleSheet("color: rgb(69, 186, 4);\n"
"background-color: rgb(35, 35, 35);")
        self.add_item_btn.setObjectName("add_item_btn")
        self.add_item_btn.clicked.connect(self.add_item)

        ##Кнопка назад
        self.to_menu_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.to_menu_btn.setGeometry(QtCore.QRect(20, 840, 121, 25))
        self.to_menu_btn.setObjectName("to_menu_btn")
        settings.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=settings)
        self.statusbar.setObjectName("statusbar")
        settings.setStatusBar(self.statusbar)

        self.retranslateUi(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "MainWindow"))
        self.list_admins_label.setText(_translate("settings", "Выберите админа из списка"))
        self.name_admin_label.setText(_translate("settings", "Имя"))
        self.del_admin_btn.setText(_translate("settings", "Удалить"))
        self.add_admin_label.setText(_translate("settings", "Добавить админа"))
        self.Name_add_admin.setText(_translate("settings", "Имя:"))
        self.add_admin_btn.setText(_translate("settings", "Добавить"))
        self.item_list.setText(_translate("settings", "Выберите товар из списка"))
        self.name_item_label.setText(_translate("settings", "Позиция"))
        self.delete_item_btn.setText(_translate("settings", "Удалить"))
        self.item_name_label.setText(_translate("settings", "Наименование"))
        self.item_cost_label.setText(_translate("settings", "Цена"))
        self.add_item_btn.setText(_translate("settings", "Добавить"))
        self.to_menu_btn.setText(_translate("settings", "Назад"))

    #####################
    ##Активаторы кнопок##
    #####################
    def activate_add_admin(self):
        self.add_admin_btn.setEnabled(True)

    def activate_add_item(self):
        self.add_item_btn.setEnabled(True)


    ######################################
    ##Добавление/удаление администратора##
    ######################################
    def add_admin(self):
        self.admin_name = self.add_admin_text_field.toPlainText()
        if self.admin_name == '':
            self.error_admin_label.setVisible(True)
        elif self.admin_name == ' ':
            self.error_admin_label.setVisible(True)     
        else:
            cur.execute(f'INSERT INTO admins VALUES("{self.admin_name}")')
            conn.commit()
            self.List_admins_widget.addItem(self.admin_name)
            self.error_admin_label.setVisible(False)
        self.add_admin_text_field.clear()


    def admin_name_clicked(self):
        self.name_admin_label.setVisible(True)
        self.del_admin_btn.setVisible(True)
        name = self.List_admins_widget.currentItem()
        self.name_admin_label.setText(str(name.text()))

    def admin_del(self):
        name = self.List_admins_widget.currentItem()                               #Получаем выбраннй элемент
        el = self.List_admins_widget.indexFromItem(name).row()                     #Получаем его номер
        cur.execute(f'DELETE FROM admins WHERE name LIKE "{str(name.text())}"')    #Закидываем имя в бд
        conn.commit()
        self.List_admins_widget.takeItem(el)                                       #Удаляем из списка
        self.del_admin_btn.setVisible(False)                                       #Офаем кнопку и имя
        self.name_admin_label.setVisible(False)



    def add_item(self):
        item_name = self.Item_name_field.toPlainText()
        item_cost = self.doubleSpinBox.value()
        if item_cost == 0:
            self.error_position_label.setVisible(True)
        elif item_name == '' or item_name == ' ':
            self.error_position_label.setVisible(True)
        else:
            cur.execute(f'INSERT INTO positions VALUES("{item_name}", "{item_cost}")')
            conn.commit()
            self.error_position_label.setVisible(False)
            self.list_item_widget.addItem(f'{item_name} | {item_cost}')
        self.Item_name_field.clear()
        self.doubleSpinBox.setValue(0)


    def item_clicked(self):
        item = self.list_item_widget.currentItem()
        self.name_item_label.setText(str(item.text()))
        self.delete_item_btn.setVisible(True)
        self.name_item_label.setVisible(True)

    def del_item(self):
        item = self.list_item_widget.currentItem()
        item_position = self.list_item_widget.indexFromItem(item).row()
        name = str(item.text()).split(" |")[0]
        cur.execute(f'DELETE FROM positions WHERE name = "{name}"')
        conn.commit()
        self.list_item_widget.takeItem(item_position)
        self.delete_item_btn.setVisible(False)
        self.name_item_label.setVisible(False)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settings = QtWidgets.QMainWindow()
    ui = Ui_settings()
    ui.setupUi(settings)
    settings.show()
    sys.exit(app.exec())
