# Form implementation generated from reading ui file 'Colizeum Tool - untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import telebot
import datetime
import sqlite3

from PyQt6.QtCore import QTimer
from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget
import sys
from PyQt6 import QtCore, QtGui, QtWidgets



bot = telebot.TeleBot('5834237694:AAE0TJdYohtj69L6jsXmD2MB0vFcsWB8tpA')
############
##Database##
############
conn = sqlite3.connect('CIS_admin_helper.db')
cur = conn.cursor()
cur.execute('CREATE TABLE IF NOT EXISTS inventory(date TEXT, admin TEXT, itog TEXT)')
cur.execute('CREATE TABLE IF NOT EXISTS admin_bar(date TEXT, admin TEXT, position TEXT, value FLOAT, cost FLOAT)')
cur.execute('CREATE TABLE IF NOT EXISTS admins(name TEXT)')
cur.execute('CREATE TABLE IF NOT EXISTS positions (name TEXT, price FLOAT)')


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(850, 900)
        self.centralwidget = QtWidgets.QWidget(parent=settings)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 491, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        ##################
        ##Список админов##
        ##################
        self.List_admins_widget = QtWidgets.QListWidget(parent=self.verticalLayoutWidget)
        self.List_admins_widget.setObjectName("List_admins_widget")
        self.List_admins_widget.clicked.connect(self.admin_name_clicked)
        self.verticalLayout.addWidget(self.List_admins_widget)
        cur.execute('SELECT * FROM admins')
        admins = cur.fetchall()
        for admin in admins:
            self.List_admins_widget.addItem(admin[0])

        ########################
        ##Выбранное имя админа##
        ########################
        self.list_admins_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.list_admins_label.setGeometry(QtCore.QRect(20, 20, 281, 17))
        self.list_admins_label.setObjectName("list_admins_label")

        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 270, 321, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")

        ######################
        ##Текст ошибка админ##
        ######################
        self.error_admin_label =QtWidgets.QLabel(parent=self.centralwidget)
        self.error_admin_label.setVisible(False)
        self.error_admin_label.setGeometry(750,90,61,31)
        self.error_admin_label.setText('Ошибка')
        self.error_admin_label.setStyleSheet("color: rgb(192, 28, 40);")

        ########################
        ##Текст ошибка позиция##
        ########################
        self.error_position_label =QtWidgets.QLabel(parent=self.centralwidget)
        self.error_position_label.setVisible(False)
        self.error_position_label.setGeometry(670,450,61,21)
        self.error_position_label.setText('Ошибка')
        self.error_position_label.setStyleSheet("color: rgb(192, 28, 40);")

        self.name_admin_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.name_admin_label.setVisible(False)
        self.name_admin_label.setObjectName("name_admin_label")
        self.horizontalLayout.addWidget(self.name_admin_label)
        self.del_admin_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.del_admin_btn.setVisible(False)
        self.del_admin_btn.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"color: rgb(192, 28, 40);")
        self.del_admin_btn.setObjectName("del_admin_btn")
        self.del_admin_btn.clicked.connect(self.admin_del)
        self.horizontalLayout.addWidget(self.del_admin_btn)
        self.add_admin_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.add_admin_label.setGeometry(QtCore.QRect(530, 20, 171, 17))
        self.add_admin_label.setObjectName("add_admin_label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(530, 50, 281, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Name_add_admin = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.Name_add_admin.setObjectName("Name_add_admin")
        self.horizontalLayout_2.addWidget(self.Name_add_admin)
        self.add_admin_text_field = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_2)
        self.add_admin_text_field.setObjectName("add_admin_text_field")
        self.horizontalLayout_2.addWidget(self.add_admin_text_field)
        self.add_admin_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.add_admin_btn.setEnabled(False)
        self.add_admin_btn.setStyleSheet("color: rgb(69, 186, 4);\n"
"background-color: rgb(35, 35, 35);")
        self.add_admin_btn.setObjectName("add_admin_btn")
        self.add_admin_btn.clicked.connect(self.add_admin)
        self.horizontalLayout_2.addWidget(self.add_admin_btn)
        self.add_admin_text_field.textChanged.connect(self.activate_add_admin)        #Активируем кнопку
        self.item_list = QtWidgets.QLabel(parent=self.centralwidget)
        self.item_list.setGeometry(QtCore.QRect(20, 330, 251, 17))
        self.item_list.setObjectName("item_list")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 360, 491, 411))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        ###########################
        ##Список с позициями бара##
        ###########################
        self.list_item_widget = QtWidgets.QListWidget(parent=self.verticalLayoutWidget_2)
        self.list_item_widget.setObjectName("list_item_widget")
        self.verticalLayout_2.addWidget(self.list_item_widget)
        self.list_item_widget.clicked.connect(self.item_clicked)
        cur.execute('SELECT * FROM positions')
        self.items = cur.fetchall()
        for item in self.items:
            self.list_item_widget.addItem(f'{item[0]} | {item[1]}')


        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 780, 321, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        ##################################
        ##Наименование выбранной позиции##
        ##################################
        self.name_item_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.name_item_label.setVisible(False)
        self.name_item_label.setObjectName("name_item_label")
        self.horizontalLayout_3.addWidget(self.name_item_label)

        ###########################
        ##Кнопка удаления позиции##
        ###########################
        self.delete_item_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.delete_item_btn.setVisible(False)
        self.delete_item_btn.setStyleSheet("color: rgb(192, 28, 40);\n"
"background-color: rgb(35, 35, 35);")
        self.delete_item_btn.setObjectName("delete_item_btn")
        self.delete_item_btn.clicked.connect(self.del_item)

        self.horizontalLayout_3.addWidget(self.delete_item_btn)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(530, 360, 291, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.item_name_label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.item_name_label.setObjectName("item_name_label")
        self.gridLayout.addWidget(self.item_name_label, 0, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget)
        self.doubleSpinBox.setMaximum(99999999.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.Item_name_field = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.Item_name_field.setObjectName("Item_name_field")
        self.Item_name_field.textChanged.connect(self.activate_add_item)      #Активируем кнопку
        self.gridLayout.addWidget(self.Item_name_field, 0, 1, 1, 1)

        ###Стоимость позиции
        self.item_cost_label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.item_cost_label.setObjectName("item_cost_label")
        self.gridLayout.addWidget(self.item_cost_label, 1, 0, 1, 1)

        ###Кнопка добавить позицию бара
        self.add_item_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_item_btn.setEnabled(False)
        self.add_item_btn.setGeometry(QtCore.QRect(740, 450, 80, 25))
        self.add_item_btn.setStyleSheet("color: rgb(69, 186, 4);\n"
"background-color: rgb(35, 35, 35);")
        self.add_item_btn.setObjectName("add_item_btn")
        self.add_item_btn.clicked.connect(self.add_item)

        ##Кнопка назад
        self.to_menu_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.to_menu_btn.setGeometry(QtCore.QRect(20, 840, 121, 25))
        self.to_menu_btn.setObjectName("to_menu_btn")
        self.to_menu_btn.clicked.connect(self.to_menu)
        settings.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=settings)
        self.statusbar.setObjectName("statusbar")
        settings.setStatusBar(self.statusbar)

        self.retranslateUi(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "MainWindow"))
        self.list_admins_label.setText(_translate("settings", "Выберите админа из списка"))
        self.name_admin_label.setText(_translate("settings", "Имя"))
        self.del_admin_btn.setText(_translate("settings", "Удалить"))
        self.add_admin_label.setText(_translate("settings", "Добавить админа"))
        self.Name_add_admin.setText(_translate("settings", "Имя:"))
        self.add_admin_btn.setText(_translate("settings", "Добавить"))
        self.item_list.setText(_translate("settings", "Выберите товар из списка"))
        self.name_item_label.setText(_translate("settings", "Позиция"))
        self.delete_item_btn.setText(_translate("settings", "Удалить"))
        self.item_name_label.setText(_translate("settings", "Наименование"))
        self.item_cost_label.setText(_translate("settings", "Цена"))
        self.add_item_btn.setText(_translate("settings", "Добавить"))
        self.to_menu_btn.setText(_translate("settings", "Назад"))

    #####################
    ##Активаторы кнопок##
    #####################
    def activate_add_admin(self):
        self.add_admin_btn.setEnabled(True)

    def activate_add_item(self):
        self.add_item_btn.setEnabled(True)


    ######################################
    ##Добавление/удаление администратора##
    ######################################
    def add_admin(self):
        self.admin_name = self.add_admin_text_field.toPlainText()
        if self.admin_name == '':
            self.error_admin_label.setVisible(True)
        elif self.admin_name == ' ':
            self.error_admin_label.setVisible(True)     
        else:
            cur.execute(f'INSERT INTO admins VALUES("{self.admin_name}")')
            conn.commit()
            self.List_admins_widget.addItem(self.admin_name)
            self.error_admin_label.setVisible(False)
        self.add_admin_text_field.clear()



    def admin_name_clicked(self):
        self.name_admin_label.setVisible(True)
        self.del_admin_btn.setVisible(True)
        name = self.List_admins_widget.currentItem()
        self.name_admin_label.setText(str(name.text()))

    def admin_del(self):
        name = self.List_admins_widget.currentItem()                               #Получаем выбраннй элемент
        el = self.List_admins_widget.indexFromItem(name).row()                     #Получаем его номер
        cur.execute(f'DELETE FROM admins WHERE name LIKE "{str(name.text())}"')    #Закидываем имя в бд
        conn.commit()
        self.List_admins_widget.takeItem(el)                                       #Удаляем из списка
        self.del_admin_btn.setVisible(False)                                       #Офаем кнопку и имя
        self.name_admin_label.setVisible(False)



    def add_item(self):
        item_name = self.Item_name_field.toPlainText()
        item_cost = self.doubleSpinBox.value()
        if item_cost == 0:
            self.error_position_label.setVisible(True)
        elif item_name == '' or item_name == ' ':
            self.error_position_label.setVisible(True)
        else:
            cur.execute(f'INSERT INTO positions VALUES("{item_name}", "{item_cost}")')
            conn.commit()
            self.error_position_label.setVisible(False)
            self.list_item_widget.addItem(f'{item_name} | {item_cost}')
        self.Item_name_field.clear()
        self.doubleSpinBox.setValue(0)


    def item_clicked(self):
        item = self.list_item_widget.currentItem()
        self.name_item_label.setText(str(item.text()))
        self.delete_item_btn.setVisible(True)
        self.name_item_label.setVisible(True)

    def del_item(self):
        item = self.list_item_widget.currentItem()
        item_position = self.list_item_widget.indexFromItem(item).row()
        name = str(item.text()).split(" |")[0]
        cur.execute(f'DELETE FROM positions WHERE name = "{name}"')
        conn.commit()
        self.list_item_widget.takeItem(item_position)
        self.delete_item_btn.setVisible(False)
        self.name_item_label.setVisible(False)

    def to_menu(self):
        settings_window.hide()
        MainWindow.show()



class Ui_Inv_history(object):
    def setupUi(self, Inv_history):
        Inv_history.setObjectName("Inv_history")
        Inv_history.resize(400, 800)
        self.centralwidget = QtWidgets.QWidget(parent=Inv_history)
        self.centralwidget.setObjectName("centralwidget")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(20, 750, 111, 25))
        self.back.setObjectName("back")
        self.back.clicked.connect(self.to_menu)
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 350, 711))
        self.textBrowser.setObjectName("textBrowser")
        cur.execute('SELECT * FROM inventory')
        result = cur.fetchall()
        l = 0
        for i in result:
            self.textBrowser.insertPlainText(f'{result[l][0]} - {result[l][1]}\n\n{result[l][2]}\n\n')
            l = l+1
        Inv_history.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Inv_history)
        self.statusbar.setObjectName("statusbar")
        Inv_history.setStatusBar(self.statusbar)

        self.retranslateUi(Inv_history)
        QtCore.QMetaObject.connectSlotsByName(Inv_history)

    def retranslateUi(self, Inv_history):
        _translate = QtCore.QCoreApplication.translate
        Inv_history.setWindowTitle(_translate("Inv_history", "MainWindow"))
        self.back.setText(_translate("Inv_history", "Назад"))

    def to_menu(self):
        inv_history.hide()
        MainWindow.show()

class Ui_Bar(object):
    def setupUi(self, Bar):
        Bar.setObjectName("Bar")
        Bar.resize(416, 751)
        self.centralwidget = QtWidgets.QWidget(parent=Bar)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 70, 261, 594))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.drink5 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.drink5.setWrapping(False)
        self.drink5.setFrame(False)
        self.drink5.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drink5.setDecimals(0)
        self.drink5.setMaximum(1000.0)
        self.drink5.setObjectName("drink5")
        self.verticalLayout_2.addWidget(self.drink5)
        self.small_drink = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.small_drink.setWrapping(False)
        self.small_drink.setFrame(False)
        self.small_drink.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.small_drink.setDecimals(0)
        self.small_drink.setMaximum(1000.0)
        self.small_drink.setObjectName("small_drink")
        self.verticalLayout_2.addWidget(self.small_drink)
        self.genezis = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.genezis.setWrapping(False)
        self.genezis.setFrame(False)
        self.genezis.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.genezis.setDecimals(0)
        self.genezis.setMaximum(1000.0)
        self.genezis.setObjectName("genezis")
        self.verticalLayout_2.addWidget(self.genezis)
        self.eon = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.eon.setWrapping(False)
        self.eon.setFrame(False)
        self.eon.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.eon.setDecimals(0)
        self.eon.setMaximum(1000.0)
        self.eon.setObjectName("eon")
        self.verticalLayout_2.addWidget(self.eon)
        self.Burn = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Burn.setWrapping(False)
        self.Burn.setFrame(False)
        self.Burn.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Burn.setDecimals(0)
        self.Burn.setMaximum(1000.0)
        self.Burn.setObjectName("Burn")
        self.verticalLayout_2.addWidget(self.Burn)
        self.adrenaline = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.adrenaline.setWrapping(False)
        self.adrenaline.setFrame(False)
        self.adrenaline.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.adrenaline.setDecimals(0)
        self.adrenaline.setMaximum(1000.0)
        self.adrenaline.setObjectName("adrenaline")
        self.verticalLayout_2.addWidget(self.adrenaline)
        self.Cyberwater = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Cyberwater.setWrapping(False)
        self.Cyberwater.setFrame(False)
        self.Cyberwater.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Cyberwater.setDecimals(0)
        self.Cyberwater.setMaximum(1000.0)
        self.Cyberwater.setObjectName("Cyberwater")
        self.verticalLayout_2.addWidget(self.Cyberwater)
        self.water = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.water.setWrapping(False)
        self.water.setFrame(False)
        self.water.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.water.setDecimals(0)
        self.water.setMaximum(1000.0)
        self.water.setObjectName("water")
        self.verticalLayout_2.addWidget(self.water)
        self.Chokolate = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Chokolate.setWrapping(False)
        self.Chokolate.setFrame(False)
        self.Chokolate.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Chokolate.setDecimals(0)
        self.Chokolate.setMaximum(1000.0)
        self.Chokolate.setObjectName("Chokolate")
        self.verticalLayout_2.addWidget(self.Chokolate)
        self.Sandwich = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Sandwich.setWrapping(False)
        self.Sandwich.setFrame(False)
        self.Sandwich.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Sandwich.setDecimals(0)
        self.Sandwich.setMaximum(1000.0)
        self.Sandwich.setObjectName("Sandwich")
        self.verticalLayout_2.addWidget(self.Sandwich)
        self.roll = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.roll.setWrapping(False)
        self.roll.setFrame(False)
        self.roll.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.roll.setDecimals(0)
        self.roll.setMaximum(1000.0)
        self.roll.setObjectName("roll")
        self.verticalLayout_2.addWidget(self.roll)
        self.Soak = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Soak.setWrapping(False)
        self.Soak.setFrame(False)
        self.Soak.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Soak.setDecimals(0)
        self.Soak.setMaximum(1000.0)
        self.Soak.setObjectName("Soak")
        self.verticalLayout_2.addWidget(self.Soak)
        self.Juice = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Juice.setWrapping(False)
        self.Juice.setFrame(False)
        self.Juice.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Juice.setDecimals(0)
        self.Juice.setMaximum(1000.0)
        self.Juice.setObjectName("Juice")
        self.verticalLayout_2.addWidget(self.Juice)
        self.benergy = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.benergy.setWrapping(False)
        self.benergy.setFrame(False)
        self.benergy.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.benergy.setDecimals(0)
        self.benergy.setMaximum(1000.0)
        self.benergy.setObjectName("benergy")
        self.verticalLayout_2.addWidget(self.benergy)
        self.powercell = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.powercell.setWrapping(False)
        self.powercell.setFrame(False)
        self.powercell.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.powercell.setDecimals(0)
        self.powercell.setMaximum(1000.0)
        self.powercell.setObjectName("powercell")
        self.verticalLayout_2.addWidget(self.powercell)
        self.gorilla = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.gorilla.setWrapping(False)
        self.gorilla.setFrame(False)
        self.gorilla.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.gorilla.setDecimals(0)
        self.gorilla.setMaximum(1000.0)
        self.gorilla.setObjectName("gorilla")
        self.verticalLayout_2.addWidget(self.gorilla)
        self.Flash = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Flash.setWrapping(False)
        self.Flash.setFrame(False)
        self.Flash.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Flash.setDecimals(0)
        self.Flash.setMaximum(1000.0)
        self.Flash.setObjectName("Flash")
        self.verticalLayout_2.addWidget(self.Flash)
        self.obed = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.obed.setWrapping(False)
        self.obed.setFrame(False)
        self.obed.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.obed.setDecimals(0)
        self.obed.setMaximum(1000.0)
        self.obed.setObjectName("obed")
        self.verticalLayout_2.addWidget(self.obed)
        self.oni120 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.oni120.setWrapping(False)
        self.oni120.setFrame(False)
        self.oni120.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.oni120.setDecimals(0)
        self.oni120.setMaximum(1000.0)
        self.oni120.setObjectName("oni120")
        self.verticalLayout_2.addWidget(self.oni120)
        self.oni150 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.oni150.setWrapping(False)
        self.oni150.setFrame(False)
        self.oni150.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.oni150.setDecimals(0)
        self.oni150.setMaximum(1000.0)
        self.oni150.setObjectName("oni150")
        self.verticalLayout_2.addWidget(self.oni150)
        self.Flum = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.Flum.setWrapping(False)
        self.Flum.setFrame(False)
        self.Flum.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Flum.setDecimals(0)
        self.Flum.setMaximum(1000.0)
        self.Flum.setObjectName("Flum")
        self.verticalLayout_2.addWidget(self.Flum)
        self.tornado = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.tornado.setWrapping(False)
        self.tornado.setFrame(False)
        self.tornado.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.tornado.setDecimals(0)
        self.tornado.setMaximum(1000.0)
        self.tornado.setObjectName("tornado")
        self.verticalLayout_2.addWidget(self.tornado)
        self.water_3 = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget)
        self.water_3.setWrapping(False)
        self.water_3.setFrame(False)
        self.water_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.water_3.setDecimals(0)
        self.water_3.setMaximum(1000.0)
        self.water_3.setObjectName("water_3")
        self.verticalLayout_2.addWidget(self.water_3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 70, 111, 591))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_4.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.send = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send.setGeometry(QtCore.QRect(290, 680, 89, 25))
        self.send.setObjectName("send")
        self.send.clicked.connect(self.send_result)
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(20, 680, 89, 25))
        self.back.setObjectName("back")
        self.back.clicked.connect(self.go_back)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 371, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        cur.execute('SELECT * FROM admins')
        self.admins = cur.fetchall()
        for i in self.admins:
            self.comboBox.addItem(i[0])
        self.horizontalLayout.addWidget(self.comboBox)
        self.horizontalLayout.setStretch(1, 4)
        Bar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Bar)
        self.statusbar.setObjectName("statusbar")
        Bar.setStatusBar(self.statusbar)

        self.retranslateUi(Bar)
        QtCore.QMetaObject.connectSlotsByName(Bar)

    def retranslateUi(self, Bar):
        _translate = QtCore.QCoreApplication.translate
        Bar.setWindowTitle(_translate("Bar", "Бар админ"))
        self.label_2.setText(_translate("Bar", "Напиток 0,5"))
        self.label_3.setText(_translate("Bar", "Напиток 0,33"))
        self.label_4.setText(_translate("Bar", "Genezis"))
        self.label_5.setText(_translate("Bar", "E-on"))
        self.label_6.setText(_translate("Bar", "Burn"))
        self.label_7.setText(_translate("Bar", "Adrenaline"))
        self.label_8.setText(_translate("Bar", "Cyberwater"))
        self.label_9.setText(_translate("Bar", "Вода"))
        self.label_10.setText(_translate("Bar", "Шоколад"))
        self.label_11.setText(_translate("Bar", "Сэндвич"))
        self.label_12.setText(_translate("Bar", "Сэндвич ролл"))
        self.label_13.setText(_translate("Bar", "Soak"))
        self.label_14.setText(_translate("Bar", "Соки"))
        self.label_15.setText(_translate("Bar", "benergy"))
        self.label_16.setText(_translate("Bar", "Powercell"))
        self.label_17.setText(_translate("Bar", "Gorilla"))
        self.label_18.setText(_translate("Bar", "Flash"))
        self.label_19.setText(_translate("Bar", "Обед"))
        self.label_20.setText(_translate("Bar", "Онигири 120"))
        self.label_21.setText(_translate("Bar", "Онигири 150"))
        self.label_22.setText(_translate("Bar", "Flum"))
        self.label_23.setText(_translate("Bar", "Tornado"))
        self.label_24.setText(_translate("Bar", "Чай Gorilla"))
        self.send.setText(_translate("Bar", "Отправить"))
        self.back.setText(_translate("Bar", "Назад"))
        self.label.setText(_translate("Bar", "Имя админа"))

    def update_admins(self):
        self.comboBox.clear()
        cur.execute('SELECT * FROM admins')
        self.admins = cur.fetchall()
        for i in self.admins:
            self.comboBox.addItem(i[0])



    def send_result(self):
        admin_name = self.comboBox.currentText()
        powercell = {
            'name': 'Powercell',
            'price' : 130,
            'value': self.powercell.value()
        }
        gorilla = {
            'name' : 'Gorilla',
            'price' : 120,
            'value' : self.gorilla.value()
        }
        flash = {
            'name' : 'Flash',
            'price' : 100,
            'value' : self.Flash.value()
        }
        obed = {
            'name' : 'Обед',
            'price' : 200,
            'value' : self.obed.value()
        }
        oni_150 = {
            'name' : 'Онигири 150',
            'price' : 150,
            'value' : self.oni150.value()
        }
        oni_120 = {
            'name' : 'Онигири 120',
            'price' : 120,
            'value' : self.oni120.value()
        }
        flum = {
            'name' : 'Flum',
            'price' : 1400,
            'value' : self.Flum.value()
        }
        benergy = {
            'name' : 'Benergy',
            'price' : 130,
            'value' : self.benergy.value()
            }
        juice = {
            'name' : 'Сок',
            'price' : 100,
            'value' : self.Juice.value()
        }
        soak = {
            'name' : 'Soak',
            'price' : 1400,
            'value' : self.Soak.value()
        }
        roll = {
            'name' : 'Сендвич ролл',
            'price' : 180,
            'value' : self.roll.value()
        }
        snwch = {
            'name' : 'Сендвич',
            'price' : 150,
            'value' : self.Sandwich.value()
        }
        choko = {
            'name' : 'Шоколадка',
            'price' : 100,
            'value' : self.Chokolate.value()
        }
        water = {
            'name' : 'Вода',
            'price' : 50,
            'value' : self.water.value()
        }
        cyberwater = {
            'name' : 'Cyberwater',
            'price' : 130,
            'value' : self.Cyberwater.value()
        }
        adrenaline = {
            'name' : 'Adrenaline',
            'price' : 150,
            'value' : self.adrenaline.value()
        }
        burn = {
            'name' : 'Burn',
            'price' : 150,
            'value' : self.Burn.value()
        }
        eon = {
            'name' : 'E-On',
            'price' : 120,
            'value' : self.eon.value()
        }
        genezis = {
            'name' : 'Genezis',
            'price' : 110,
            'value' : self.genezis.value()
        }
        drink5 = {
            'name' : 'Напиток 0.5',
            'price' : 110,
            'value' : self.drink5.value()
        }
        small_drink = {
            'name' : 'Напиток 0.33',
            'price' : 70,
            'value' : self.small_drink.value()
        }
        tornado = {
            'name' : 'Tornado',
            'price' : 100,
            'value' : self.tornado.value()
        }
        tea_gorilla = {
            'name' : 'Чай Gorilla',
            'price' : 100,
            'value' : self.water_3.value()
        }
        item_list = [powercell,gorilla,flash,obed,oni_120,oni_150,flum,benergy,juice,soak,roll,snwch,choko,water,cyberwater,adrenaline,burn,eon,genezis,drink5,small_drink, tornado, tea_gorilla]
        for item in item_list:
            if item['value'] > 0:
                name, value = item['name'], item['value']
                cost = value * item['price']
                today = datetime.datetime.now()
                to_insrt = f'{today.year}-{today.month}-{today.day}'
                cur.execute(f'INSERT INTO admin_bar VALUES("{to_insrt}", "{admin_name}", "{name}", "{value}", "{cost}")')
                conn.commit()

    def go_back(self):
        window_bar.close()
        MainWindow.show()


class Inventory(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(616, 797)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.to_menu_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.to_menu_btn.setGeometry(QtCore.QRect(20, 720, 89, 25))
        self.to_menu_btn.setObjectName("pushButton")
        self.to_menu_btn.clicked.connect(self.go_back)
        self.send_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send_btn.setGeometry(QtCore.QRect(490, 720, 89, 25))
        self.send_btn.setObjectName("pushButton_2")
        self.send_btn.clicked.connect(self.send)
        self.admin_name = QtWidgets.QComboBox(parent=self.centralwidget)
        self.admin_name.setGeometry(QtCore.QRect(180, 650, 201, 31))
        self.admin_name.setObjectName("textEdit")
        cur.execute('SELECT * FROM admins')
        self.admins = cur.fetchall()
        for admin in self.admins:
            self.admin_name.addItem(str(admin[0]))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Colizeum Tool"))
        self.to_menu_btn.setText(_translate("MainWindow", "Назад"))
        self.send_btn.setText(_translate("MainWindow", "Отправить"))



    def send(self):                                 #Считывание и отправка данных в тг (сделать запись в бд)
       self.admin = self.admin_name.currentText()        
       big_1 = self.drink5.value()
       big_2 = self.drink5_1.value()
       small_1 = self.small_drink.value()
       small_2 = self.small_drink_1.value()
       powercell_itog = self.powercell_1.value() - self.powercell.value()
       gorilla_itog = self.Gorilla_1.value() - self.gorilla.value()
       flah_itg = self.Flash_1.value() - self.Flash.value()
       obed_itg = self.obed_1.value() - self.obed.value()
       oni_150_itg = self.oni150_1.value() - self.oni150.value()
       flum_itg = self.flum_1.value() - self.Flum.value()
       benergy_itog = self.benergy_1.value() - self.benergy.value()
       jc_itg = self.juice_1.value() - self.Juice.value()
       Soak_itg = self.Soak_1.value() - self.Soak.value()
       roll_itg = self.roll_1.value() - self.roll.value()
       sndw_itg = self.sandwitch_1.value() - self.Sandwich.value()
       chokolate_itog = self.choko_1.value() - self.Chokolate.value()
       wtr_itg = self.Water_1.value() - self.water.value()
       cyberwater_itog = self.Cyberwater_1.value() - self.Cyberwater.value()
       arenaline_itog = self.adrenaline_1.value() - self.adrenaline.value()
       burn_itog = self.burn_1.value() - self.Burn.value()
       eon_itog = self.eon_2.value() - self.eon.value()
       genezis_itog = self.genezis_2.value() - self.genezis.value()
       onigiri_120_itog = self.oni120_1.value() - self.oni120.value()
       drink_big_itog = big_2-big_1
       small_drink_itog = small_2 - small_1
       time_now = datetime.datetime.now()



       result = open('result.txt', 'w')
       today = datetime.datetime.now()
       self.to_insrt = f'{today.year}-{today.month}-{today.day}'
       self.itog = f'Powercell - ({powercell_itog})\nGorilla - ({gorilla_itog})\nFlash - ({flah_itg})\nОбед - ({obed_itg})\nОнигири 150 - ({oni_150_itg})\nОнигири 120 - ({onigiri_120_itog})\nFlum - ({flum_itg})\nBenergy - ({benergy_itog})\nСок - ({jc_itg})\nSoak - ({Soak_itg})\nРолл - ({roll_itg})\nСендвич - ({sndw_itg})\nШоколад - ({chokolate_itog})\nВода - ({wtr_itg})\nCyberwater - ({cyberwater_itog})\nAdrenaline - ({arenaline_itog})\nBurn - ({burn_itog})\nE-on - ({eon_itog})\nGenezis - ({genezis_itog})\nНапиток 0,5 - ({drink_big_itog})\nНапиток 0,33 - ({small_drink_itog})'
       cur.execute(f'INSERT INTO inventory VALUES("{self.to_insrt}","{self.admin}","{self.itog}")')
       conn.commit()
       result.write(f'Дата: {self.to_insrt}\nВремя: {time_now.hour}:{time_now.minute}\nАдминистратор: {self.admin}\n\nPowercell - ({powercell_itog})\nGorilla - ({gorilla_itog})\nFlash - ({flah_itg})\nОбед - ({obed_itg})\nОнигири 150 - ({oni_150_itg})\nОнигири 120 - ({onigiri_120_itog})\nFlum - ({flum_itg})\nBenergy - ({benergy_itog})\nСок - ({jc_itg})\nSoak - ({Soak_itg})\nРолл - ({roll_itg})\nСендвич - ({sndw_itg})\nШоколад - ({chokolate_itog})\nВода - ({wtr_itg})\nCyberwater - ({cyberwater_itog})\nAdrenaline - ({arenaline_itog})\nBurn - ({burn_itog})\nE-on - ({eon_itog})\nGenezis - ({genezis_itog})\nНапиток 0,5 - ({drink_big_itog})\nНапиток 0,33 - ({small_drink_itog})')
       result.close()
       self.send_tg()

    def go_back(self):  #Кнопка назад (на винде криво работает)
        window_inv.hide()
        MainWindow.show()

    def send_tg(self):          #Отправка в телегу
        self.results = open('result.txt', 'r')
        self.msg = self.results.read()
        bot.send_message(412997019, self.msg)

class Ui_MainWindow(object):                #Основное окно (меню)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{background-image: url(background.png);\nbackground-position: absolute;}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 100, 260, 30))
        self.pushButton.setStyleSheet("background-color: rgb(245, 232, 50);\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("Inventarization")
        self.pushButton.clicked.connect(self.invent)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 170, 260, 30))
        self.pushButton_2.setStyleSheet("background-color: rgb(245, 232, 50);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.bar_administrator)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 240, 260, 30))
        self.pushButton_3.setStyleSheet("background-color: rgb(245, 232, 50);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.history_inv)
        self.exit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(170, 700, 260, 30))
        self.exit_btn.setStyleSheet("background-color: rgb(245, 232, 50);\n"
"color: rgb(0, 0, 0);")
        self.exit_btn.setObjectName("exit_btn")
        self.exit_btn.clicked.connect(exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        ###################
        ##Кнопка настроек##
        ###################
        self.settings_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.settings_btn.setGeometry(QtCore.QRect(170, 630, 260, 30))
        self.settings_btn.setStyleSheet("background-color: rgb(245, 232, 50);\n"
"color: rgb(0, 0, 0);")
        self.settings_btn.setObjectName("setting_btn")
        self.settings_btn.clicked.connect(self.settings)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Colizeum Tool"))
        self.settings_btn.setText(_translate('Mainwindow', "Настройки"))
        self.pushButton.setText(_translate("MainWindow", "Инвентаризация"))
        self.pushButton_2.setText(_translate("MainWindow", "Бар администратор"))
        self.pushButton_3.setText(_translate("MainWindow", "История инвентаризаций"))
        self.exit_btn.setText(_translate("MainWindow", "Выход"))

    def invent(self):
        MainWindow.hide()
        window_inv.show()

    def bar_administrator(self):
        MainWindow.hide()
        window_bar.update()
        window_bar.show()
        
    def history_inv(self):
        MainWindow.hide()
        inv_history.show()

    def settings(self):
        MainWindow.hide()
        settings_window.show()
        



        
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    bar = Ui_Bar()

    #################
    ##Основное окно##
    #################
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    ##########################
    ##История инвентаризаций##
    ##########################
    inv_history = QtWidgets.QMainWindow()
    inv_hist_ui = Ui_Inv_history()
    inv_hist_ui.setupUi(inv_history)

    #######################
    ##Окно инвентаризации##
    #######################
    window_inv = QtWidgets.QMainWindow()
    inv = Inventory()
    inv.setupUi(window_inv)

    ##########################
    ##Окно бар администратор##
    ##########################
    window_bar = QtWidgets.QMainWindow()
    bar_wndw = Ui_Bar()
    bar_wndw.setupUi(window_bar)

    #################
    ##Окно настроек##
    #################
    settings_window = QtWidgets.QMainWindow()
    stngs_wndw = Ui_settings()
    stngs_wndw.setupUi(settings_window)

    MainWindow.show()
    sys.exit(app.exec())
    bot.polling(none_stop=True, interval=0)