# Form implementation generated from reading ui file 'abonements.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtCore import QTimer
from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget, QLineEdit
import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPainterPath

with open('style.css', 'r') as r:
    style = r.read()

with open ("style.qss", 'r') as st:
            qstyle = st.read()


class Ui_Abonements(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 262)
        MainWindow.setWindowFlag(QtCore.Qt.WindowType.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground, True )
        MainWindow.setStyleSheet(style)
        center = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr = MainWindow.frameGeometry()
        qr.moveCenter(center)
        MainWindow.move(qr.topLeft())
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet(qstyle)
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 40, 481, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setEditable(True)
        self.number_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.number_label.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.number_label.setObjectName("number_label")

        self.three_hour_big_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.three_hour_big_label.setGeometry(QtCore.QRect(10, 70, 151, 31))
        self.three_hour_big_label.setVisible(False)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.three_hour_big_label.setFont(font)
        self.three_hour_big_label.setObjectName("three_hour_big_label")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(290, 80, 16, 141))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.five_hour_big_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.five_hour_big_label.setGeometry(QtCore.QRect(310, 70, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.five_hour_big_label.setFont(font)
        self.five_hour_big_label.setVisible(False)
        self.five_hour_big_label.setObjectName("five_hour_big_label")
        self.three_status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.three_status_label.setGeometry(QtCore.QRect(10, 130, 67, 17))
        self.three_status_label.setObjectName("three_status_label")
        self.three_value_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.three_value_label.setGeometry(QtCore.QRect(90, 130, 80, 17))
        self.three_value_label.setObjectName("three_value_label")
        self.sold_three_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sold_three_btn.setGeometry(QtCore.QRect(200, 130, 89, 21))
        self.sold_three_btn.setObjectName("sold_three_btn")
        self.three_past_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.three_past_label.setGeometry(QtCore.QRect(10, 180, 67, 17))
        self.three_past_label.setObjectName("three_past_label")
        self.three_minus_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.three_minus_btn.setGeometry(QtCore.QRect(200, 180, 89, 21))
        self.three_minus_btn.setObjectName("three_minus_btn")
        self.three_past_value_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.three_past_value_label.setGeometry(QtCore.QRect(90, 180, 67, 17))
        self.three_past_value_label.setObjectName("three_past_value_label")
        self.five_minus_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.five_minus_btn.setGeometry(QtCore.QRect(500, 180, 89, 21))
        self.five_minus_btn.setObjectName("five_minus_btn")
        self.five_status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.five_status_label.setGeometry(QtCore.QRect(310, 130, 67, 17))
        self.five_status_label.setObjectName("five_status_label")
        self.five_past_value_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.five_past_value_label.setGeometry(QtCore.QRect(390, 180, 67, 17))
        self.five_past_value_label.setObjectName("five_past_value_label")
        self.five_sold_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.five_sold_btn.setGeometry(QtCore.QRect(500, 130, 89, 21))
        self.five_sold_btn.setObjectName("five_sold_btn")
        self.five_past_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.five_past_label.setGeometry(QtCore.QRect(310, 180, 67, 17))
        self.five_past_label.setObjectName("five_past_label")
        self.five_status_value_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.five_status_value_label.setGeometry(QtCore.QRect(390, 130, 80, 17))
        self.five_status_value_label.setObjectName("five_status_value_label")
        self.three_minus_btn.setVisible(False)
        self.three_past_label.setVisible(False)
        self.three_past_value_label.setVisible(False)
        self.three_status_label.setVisible(False)
        self.three_value_label.setVisible(False)
        self.sold_three_btn.setVisible(False)

        self.five_minus_btn.setVisible(False)
        self.five_past_label.setVisible(False)
        self.five_past_value_label.setVisible(False)
        self.five_sold_btn.setVisible(False)
        self.five_status_label.setVisible(False)
        self.five_status_value_label.setVisible(False)
        self.back_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(10, 230, 89, 25))
        self.back_btn.setObjectName("back_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.number_label.setText(_translate("MainWindow", "Номер:"))
        self.three_hour_big_label.setText(_translate("MainWindow", "Абонемент 3 часа:"))
        self.five_hour_big_label.setText(_translate("MainWindow", "Абонемент 5 часов:"))
        self.three_status_label.setText(_translate("MainWindow", "Статус:"))
        self.three_value_label.setText(_translate("MainWindow", "Статус"))
        self.sold_three_btn.setText(_translate("MainWindow", "Продать"))
        self.three_past_label.setText(_translate("MainWindow", "Остаток:"))
        self.three_minus_btn.setText(_translate("MainWindow", "Списать"))
        self.three_past_value_label.setText(_translate("MainWindow", "Остаток"))
        self.five_minus_btn.setText(_translate("MainWindow", "Списать"))
        self.five_status_label.setText(_translate("MainWindow", "Статус:"))
        self.five_past_value_label.setText(_translate("MainWindow", "Остаток"))
        self.five_sold_btn.setText(_translate("MainWindow", "Продать"))
        self.five_past_label.setText(_translate("MainWindow", "Остаток:"))
        self.five_status_value_label.setText(_translate("MainWindow", "Статус"))
        self.back_btn.setText(_translate("MainWindow", "Назад"))
