from PyQt6.QtCore import QTimer
from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget, QLineEdit
import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPainterPath

with open('style.css', 'r') as r:
    style = r.read()

with open ("style.qss", 'r') as st:
            qstyle = st.read()




class Ui_AddUser(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 600)
        MainWindow.setStyleSheet(style)
        MainWindow.setWindowFlag(QtCore.Qt.WindowType.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground, True )
        center = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr = MainWindow.frameGeometry()
        qr.moveCenter(center)
        MainWindow.move(qr.topLeft())
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet(qstyle)

        #################
        ##Кнопка выхода##
        #################
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(10, 560, 100,25))
        self.exit_btn.setText('Назад')

        self.login_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.login_label.setGeometry(QtCore.QRect(10, 60, 67, 25))
        self.login_label.setObjectName("login_label")
        self.password_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(10, 100, 67, 25))
        self.password_label.setObjectName("password_label")
        self.name_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(10, 140, 67, 25))
        self.name_label.setObjectName("name_label")
        self.surname_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.surname_label.setGeometry(QtCore.QRect(10, 180, 71, 25))
        self.surname_label.setObjectName("surname_label")
        self.post_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.post_label.setGeometry(QtCore.QRect(10, 220, 91, 25))
        self.post_label.setObjectName("post_label")
        self.login_field = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.login_field.setGeometry(QtCore.QRect(110, 60, 201, 25))
        self.login_field.setObjectName("login_field")
        self.login_field.setStyleSheet(style)
        self.password_field = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_field.setGeometry(QtCore.QRect(110, 100, 201, 25))
        self.password_field.setObjectName("password_field")
        self.password_field.setStyleSheet(style)
        self.name_field = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_field.setGeometry(QtCore.QRect(110, 140, 201, 25))
        self.name_field.setObjectName("name_field")
        self.surname_field = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.surname_field.setGeometry(QtCore.QRect(110, 180, 201, 25))
        self.surname_field.setObjectName("surname_field")
        self.add_acc_big_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.add_acc_big_label.setGeometry(QtCore.QRect(70, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.add_acc_big_label.setFont(font)
        self.add_acc_big_label.setObjectName("add_acc_big_label")
        self.post_combobox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.post_combobox.setGeometry(QtCore.QRect(110, 220, 201, 25))
        self.post_combobox.setObjectName("post_combobox")
        self.post_combobox.addItem("")
        self.post_combobox.addItem("")
        self.post_combobox.addItem("")
        self.post_combobox.addItem("")

        ###########################
        ##Кнопка добавить аккаунт##
        ###########################
        self.accept_add_admin_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.accept_add_admin_btn.setGeometry(QtCore.QRect(208, 270, 101, 31))
        self.accept_add_admin_btn.setObjectName("accept_add_admin_btn")
        self.accept_add_admin_btn.setStyleSheet(qstyle)

        self.error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(10, 271, 181, 41))
        self.error_label.setStyleSheet('color: red')
        font = QtGui.QFont()
        font.setPointSize(9)
        self.error_label.setFont(font)
        self.error_label.setObjectName("error_label")
        self.error_label.setVisible(False)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(330, 0, 20, 321))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 310, 341, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.big_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.big_label.setGeometry(QtCore.QRect(480, 10, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.big_label.setFont(font)
        self.big_label.setObjectName("big_label")

        ##################
        ##Лист аккаунтов##
        ##################
        self.acc_list_widget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.acc_list_widget.setGeometry(QtCore.QRect(360, 60, 451, 261))
        self.acc_list_widget.setObjectName("acc_list_widget")

        self.chosen_acc_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.chosen_acc_label.setGeometry(QtCore.QRect(170, 340, 491, 25))
        self.chosen_acc_label.setVisible(False)
        font = QtGui.QFont()
        font.setBold(True)
        self.chosen_acc_label.setFont(font)
        self.chosen_acc_label.setObjectName("chosen_acc_label")
        self.delete_acc_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_acc_btn.setGeometry(QtCore.QRect(720, 340, 89, 25))
        self.delete_acc_btn.setObjectName("delete_acc_btn")
        self.delete_acc_btn.setStyleSheet(qstyle)
        self.delete_acc_btn.setVisible(False)
        self.chosen_acc_text_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.chosen_acc_text_label.setGeometry(QtCore.QRect(10, 340, 161, 25))
        self.chosen_acc_text_label.setObjectName("chosen_acc_text_label")
        self.chosen_acc_text_label.setVisible(False)


        self.change_login_field = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.change_login_field.setGeometry(QtCore.QRect(10, 420, 221, 31))
        self.change_login_field.setObjectName("change_login_field")
        self.change_login_field.setVisible(False)
        self.change_login_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.change_login_label.setGeometry(QtCore.QRect(10, 390, 151, 17))
        self.change_login_label.setObjectName("change_login_label")
        self.change_login_label.setVisible(False)
        self.change_login_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.change_login_btn.setGeometry(QtCore.QRect(250, 420, 101, 31))
        self.change_login_btn.setObjectName("change_login_btn")
        self.change_login_btn.setVisible(False)

        self.change_password_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.change_password_btn.setGeometry(QtCore.QRect(250, 510, 101, 31))
        self.change_password_btn.setObjectName("change_password_btn")
        self.change_password_btn.setVisible(False)
        self.Change_password_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Change_password_label.setGeometry(QtCore.QRect(10, 480, 151, 17))
        self.Change_password_label.setObjectName("Change_password_label")
        self.Change_password_label.setVisible(False)
        self.change_password_field = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.change_password_field.setGeometry(QtCore.QRect(10, 510, 221, 31))
        self.change_password_field.setObjectName("change_password_field")
        self.change_password_field.setVisible(False)

        self.change_post_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.change_post_label.setGeometry(QtCore.QRect(460, 390, 151, 17))
        self.change_post_label.setObjectName("change_post_label")
        self.change_post_label.setVisible(False)
        self.change_post_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.change_post_btn.setGeometry(QtCore.QRect(710, 420, 101, 31))
        self.change_post_btn.setObjectName("change_post_btn")
        self.change_post_btn.setVisible(False)
        self.change_post_combobox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.change_post_combobox.setGeometry(QtCore.QRect(460, 420, 221, 31))
        self.change_post_combobox.setObjectName("change_post_combobox")
        self.change_post_combobox.setVisible(False)
        self.change_post_combobox.addItem("Администратор")
        self.change_post_combobox.addItem("Управляющий")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_label.setText(_translate("MainWindow", "Логин:"))
        self.password_label.setText(_translate("MainWindow", "Пароль:"))
        self.name_label.setText(_translate("MainWindow", "Имя:"))
        self.surname_label.setText(_translate("MainWindow", "Фамилия:"))
        self.post_label.setText(_translate("MainWindow", "Должность:"))
        self.add_acc_big_label.setText(_translate("MainWindow", "Добавить аккаунт"))
        self.post_combobox.setItemText(0, _translate("MainWindow", "Администратор"))
        self.post_combobox.setItemText(1, _translate("MainWindow", "Управляющий"))
        self.post_combobox.setItemText(2, _translate("MainWindow", "Старший администратор"))
        self.post_combobox.setItemText(3, _translate("MainWindow", "Младший администратор"))
        self.accept_add_admin_btn.setText(_translate("MainWindow", "Принять"))
        self.error_label.setText(_translate("MainWindow", "Текст ошибки"))
        self.big_label.setText(_translate("MainWindow", "Работа с аккаунтами"))
        self.chosen_acc_label.setText(_translate("MainWindow", "Аккаунт"))
        self.delete_acc_btn.setText(_translate("MainWindow", "Удалить"))
        self.chosen_acc_text_label.setText(_translate("MainWindow", "Выбранный аккаунт:"))
        self.change_login_label.setText(_translate("MainWindow", "Изменить логин:"))
        self.change_login_btn.setText(_translate("MainWindow", "Изменить"))
        self.change_password_btn.setText(_translate("MainWindow", "Изменить"))
        self.Change_password_label.setText(_translate("MainWindow", "Изменить пароль:"))
        self.change_post_label.setText(_translate("MainWindow", "Изменить должность:"))
        self.change_post_btn.setText(_translate("MainWindow", "Изменить"))