# Form implementation generated from reading ui file '/home/author/Bar_bot/Ignore/Admin_bar.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Bar(object):
    def setupUi(self, Bar):
        Bar.setObjectName("Bar")
        Bar.resize(416, 751)
        center = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr = Bar.frameGeometry()
        qr.moveCenter(center)
        Bar.move(qr.topLeft())
        self.centralwidget = QtWidgets.QWidget(parent=Bar)
        self.centralwidget.setObjectName("centralwidget")
        self.send = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send.setGeometry(QtCore.QRect(290, 700, 89, 25))
        self.send.setObjectName("send")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(20, 700, 89, 25))
        self.back.setObjectName("back")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 70, 391, 601))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 389, 599))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 30, 280, 25))
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.admin_name_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.admin_name_label.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.admin_name_label.setObjectName("admin_name_label")
        Bar.setCentralWidget(self.centralwidget)

        self.retranslateUi(Bar)
        QtCore.QMetaObject.connectSlotsByName(Bar)

    def retranslateUi(self, Bar):
        _translate = QtCore.QCoreApplication.translate
        Bar.setWindowTitle(_translate("Bar", "Бар админ"))
        self.send.setText(_translate("Bar", "Отправить"))
        self.back.setText(_translate("Bar", "Назад"))
        self.admin_name_label.setText(_translate("Bar", "Имя админа:"))
