# Form implementation generated from reading ui file '/home/author/Bar_bot/Ui/Authorize.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import typing
import telebot
import datetime
import sqlite3
import configparser
import os, time
import hashlib

from PyQt6 import QtCore, QtWidgets, QtGui
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget, QLineEdit

with open('style.qss', 'r') as file:
    qstyle = file.read()



class Ui_Authorization_window(object):
    def setupUi(self, Authorization):
        Authorization.setObjectName("MainWindow")
        Authorization.setFixedSize(600, 400)
        Authorization.setStyleSheet("")
        Authorization.setWindowFlag(QtCore.Qt.WindowType.FramelessWindowHint)
        Authorization.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground, True )
        self.centralwidget = QtWidgets.QWidget(parent=Authorization)
        center = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr = Authorization.frameGeometry()
        qr.moveCenter(center)
        Authorization.move(qr.topLeft())
            
        self.centralwidget.setStyleSheet(qstyle)
        self.centralwidget.setObjectName("centralwidget")

        self.etner_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.etner_btn.setGeometry(QtCore.QRect(230, 250, 151, 31))
        self.etner_btn.setStyleSheet(qstyle)
        self.etner_btn.setObjectName("enter_btn")
        self.login_field = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.login_field.setGeometry(QtCore.QRect(180, 130, 240, 30))
        self.login_field.setObjectName("login_field")
        self.login_field.setStyleSheet('background-color: rgb(45,45,45);\ncolor: white')
        self.password_field = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_field.setGeometry(QtCore.QRect(180, 190, 240, 30))
        self.password_field.setObjectName("password_field")
        self.password_field.setEchoMode(QLineEdit.EchoMode.Password)
        self.password_field.setStyleSheet('background-color: rgb(45,45,45);\ncolor: white')
        self.authorize_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.authorize_label.setGeometry(QtCore.QRect(195, 70, 210, 30))
        self.authorize_label.setStyleSheet('color:white')
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.authorize_label.setFont(font)
        self.authorize_label.setObjectName("authorize_label")
        self.close_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.close_btn.setGeometry(QtCore.QRect(10, 360, 89, 25))
        self.close_btn.setObjectName("close_btn")
        self.forgot_password_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.forgot_password_label.setGeometry(QtCore.QRect(330, 220, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(True)
        self.forgot_password_label.setFont(font)
        self.forgot_password_label.setStyleSheet(qstyle)
        self.forgot_password_label.setObjectName("forgot_password_label")
        Authorization.setCentralWidget(self.centralwidget)

        self.retranslateUi(Authorization)
        QtCore.QMetaObject.connectSlotsByName(Authorization)

    def retranslateUi(self, Authorization):
        _translate = QtCore.QCoreApplication.translate
        Authorization.setWindowTitle(_translate("Authorization", "Авторизация"))
        self.etner_btn.setText(_translate("Authorization", "Вход"))
        self.authorize_label.setText(_translate("Authorization", "Авторизация"))
        self.close_btn.setText(_translate("Authorization", "Выйти"))
        self.forgot_password_label.setText(_translate("Authorization", "Забыли пароль?"))


