# Form implementation generated from reading ui file '/home/author/Bar_bot/Ignore/Main_menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

with open('style.qss', 'r') as file:
    qstyle = file.read()

with open('style.css', 'r') as file:
    style = file.read()

class Ui_Main_Menu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        center = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr = MainWindow.frameGeometry()
        qr.moveCenter(center)
        MainWindow.move(qr.topLeft())
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet(qstyle)
        self.centralwidget.setObjectName("centralwidget_Main")
        self.inventory_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.inventory_btn.setGeometry(QtCore.QRect(170, 60, 260, 30))
        self.inventory_btn.setStyleSheet(style)
        self.inventory_btn.setObjectName("inventory_btn")
        self.admin_bar_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.admin_bar_btn.setGeometry(QtCore.QRect(170, 120, 260, 30))
        self.admin_bar_btn.setStyleSheet(style)
        self.admin_bar_btn.setObjectName("admin_bar_btn")
        self.inv_history_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.inv_history_btn.setGeometry(QtCore.QRect(170, 180, 260, 30))
        self.inv_history_btn.setStyleSheet(style)
        self.inv_history_btn.setObjectName("inv_history_btn")
        self.ex = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ex.setGeometry(QtCore.QRect(170, 700, 260, 30))
        self.ex.setStyleSheet(style)
        self.ex.setObjectName("exit")
        self.stock_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stock_btn.setGeometry(QtCore.QRect(170, 240, 260, 30))
        self.stock_btn.setStyleSheet(style)
        self.stock_btn.setObjectName("stock_btn")
        self.promo_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.promo_btn.setGeometry(QtCore.QRect(170, 300, 260, 30))
        self.promo_btn.setStyleSheet(style)
        self.promo_btn.setObjectName("promo_btn")
        self.manager_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.manager_menu.setGeometry(QtCore.QRect(170, 640, 260, 30))
        self.manager_menu.setStyleSheet(style)
        self.manager_menu.setObjectName("manager_menu")
        self.current_account = QtWidgets.QLabel(parent=self.centralwidget)
        self.current_account.setGeometry(QtCore.QRect(10, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        self.current_account.setFont(font)
        self.current_account.setObjectName("current_account")
        self.current_account.setStyleSheet('color: white')
        self.change_acc_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.change_acc_btn.setGeometry(QtCore.QRect(10, 50, 141, 31))
        self.change_acc_btn.setObjectName("change_acc_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Colizeum Tool"))
        self.inventory_btn.setText(_translate("MainWindow", "Инвентаризация"))
        self.admin_bar_btn.setText(_translate("MainWindow", "Бар администратор"))
        self.inv_history_btn.setText(_translate("MainWindow", "История инвентаризаций"))
        self.ex.setText(_translate("MainWindow", "Выход"))
        self.stock_btn.setText(_translate("MainWindow", "Склад"))
        self.promo_btn.setText(_translate("MainWindow", "Акции"))
        self.manager_menu.setText(_translate("MainWindow", "Меню управляющего"))
        self.current_account.setText(_translate("MainWindow", "Текущий аккаунт"))
        self.change_acc_btn.setText(_translate("MainWindow", "Выйти"))
