# Form implementation generated from reading ui file '/home/author/Bar_bot/Ui/manager_menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

with open('style.css', 'r') as r:
    style = r.read()

with open ("style.qss", 'r') as st:
            qstyle = st.read()

class Ui_Manager_menu(object):
    def setupUi(self, Manager_menu):
        Manager_menu.setObjectName("Manager_menu")
        Manager_menu.resize(430, 620)
        center = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr = Manager_menu.frameGeometry()
        qr.moveCenter(center)
        Manager_menu.move(qr.topLeft())
        Manager_menu.setWindowFlag(QtCore.Qt.WindowType.FramelessWindowHint)
        Manager_menu.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground, True )
        self.centralwidget = QtWidgets.QWidget(parent=Manager_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet(qstyle)
        self.settings_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.settings_btn.setGeometry(QtCore.QRect(90, 40, 250, 30))
        self.settings_btn.setObjectName("settings_btn")
        self.settings_btn.setStyleSheet(style)
        self.account_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.account_btn.setGeometry(QtCore.QRect(90, 90, 250, 30))
        self.account_btn.setObjectName("account_btn")
        self.account_btn.setStyleSheet(style)
        self.back_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(90, 550, 250, 30))
        self.back_btn.setObjectName("back_btn")
        self.back_btn.setStyleSheet(style)
        Manager_menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Manager_menu)
        QtCore.QMetaObject.connectSlotsByName(Manager_menu)

    def retranslateUi(self, Manager_menu):
        _translate = QtCore.QCoreApplication.translate
        Manager_menu.setWindowTitle(_translate("Manager_menu", "Меню управляющего"))
        self.settings_btn.setText(_translate("Manager_menu", "Настройки"))
        self.account_btn.setText(_translate("Manager_menu", "Аккаунты"))
        self.back_btn.setText(_translate("Manager_menu", "Назад"))
